---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-discord
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mautrix-discord-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: mautrix-discord-configmap
            items:
              - key: config.yaml
        - configMap:
            name: mautrix-discord-configmap
            items:
              - key: double-puppet-registration.yaml
        - configMap:
            name: mautrix-discord-configmap
            items:
              - key: registration.yaml
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: matrix
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-discord-db
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mautrix-discord-db-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: "{{ .MAUTRIX_DISCORD_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .MAUTRIX_DISCORD_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .MAUTRIX_DISCORD_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
