---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wsab
spec:
  chartRef:
    kind: OCIRepository
    name: wsab
  interval: 1h
  values:
    controllers:
      wsab:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 5.1.3@sha256:b1795982db498ed5691a7b1231f0fac7eed2a1d53e9c81b8e834d02695e76104
            env:
              TZ: Europe/London
              SABNZBD__PORT: 80
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                wsab,
                wsab.default,
                wsab.default.svc,
                wsab.default.svc.cluster,
                wsab.default.svc.cluster.local,
                wsab.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 12Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: wsab
        ports:
          http:
            port: 80
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: wsab
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      data:
        type: nfs
        server: unraid.kvshs.xyz
        path: /mnt/user/data/usenet
        globalMounts:
          - path: /data/usenet
      tmp:
        type: emptyDir
