apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:r9Xsk20tM6AR2JBGFjweIU5EcR9H2fePOLa1wzyXZS2Ny15F,iv:/yi6QgLabmWLcFbRG20G9ztRxvEeIpQaaz+mFTEwNv4=,tag:ME7+b4UdbYXAzx3OHynDCA==,type:str]
    credentials.json: ENC[AES256_GCM,data:dydz3IHEQXat5owTxoIG5afYEYXzBh4UlzJr3rnnoFO1RBuHaEF4j7PoqP15Ycf7GTB3SrtWfTLxy5Qoep3nCtK7vW7H8qcGAubHHST8ZwMBkR1gcAbayvLHCO8d82K7nlz40zfxTPavUxKZ5wGCdoJniM89fDIohg6aDenZLyjFDBHEktyK1aKlRLBZoD0cCphERXhEyW64sKP94P3teNNkINYT86swl5TVv1rCXw==,iv:1T7WREMOf4EblvcG7y5SY8nnxRsjFXa7DZJVuUzFFQg=,tag:MmQ3UKblRKjx4ZZ51DmHUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWWtXVGVXUU11ZlNxSStV
            c1JXdm9CaWhlbzFOeHdoWldNcjVRcmZFVUZNCkJLSEtocGhVdFl3TXRIVnBvS3ZR
            eW1yRnJJTWRKdDAreFZwWkxQYjlmUWsKLS0tIFJKS2JJZ0d5TzFWT2hnWGlwZTJk
            dXNwMVJaUXFTSHdGTTJtTmFQSFZKblEK/Wnbyq6l7YAUmthkifetlAebcJdr4PwN
            wzDbRPyjvigU7iosXpcOCLR/r2TvmydSPITWxX8y61biwaqTv6Cg8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-30T09:40:21Z"
    mac: ENC[AES256_GCM,data:X+AueLTxly5Q7s5PVIS9i/AZnybdDf5dNZQIAkhq8xmlCZLw7SYaLGBadr3+EQdBp5A3aGAbcHq7wVgG7oxIwW31gIi/E7kFUiY0PNw+WohTlEJcLJSQoez4lfsOhDGgMimsBovx6KZw8AZqpklpZFU5YqGMqX4QUWRsTMKEv2k=,iv:EGxad7zx2VE2BD5UPRD5DozNJ0qmBxLQ5qGAa06MbqI=,tag:4DXMxVlpF+dpk57VvDkIrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
