apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:3d8n7yx6vamonNSGxo1ccc+sgbs0uuvtGl5v1O8EBU7Gz96X+e9YYw==,iv:DJFntOe5Y7v9JQdbPUcLT+Czd0FbelJr+q1j/rDlOg0=,tag:xMH8i/6wHTON0jqU+M/BQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSEJRWHBjMy9yWEZ3aTJ6
            TC9BVk1zNnZGYkZPKzlxYWhSUjZZaFYzanpNCkxYS0YvTnduanVBQ0VkdnpYMVRL
            UEhlVUsreitjNnVHMndkUHd3SjBHamsKLS0tIHlCbFFsajZDMEYrQmNSWEUzbFdu
            ZjR4c3Vwb2hiZjJMTXVHVVc4dCszMncK+l/cFKUDgGOclTRNcSfXKriLA/lqSa4p
            oJmLfAblJAN2fAVmM4c+dTsBhjiG/IYSefqtx2lGzOKn2UtpaAzgaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T21:01:11Z"
    mac: ENC[AES256_GCM,data:8iSLI37SPbB3NsZ6pp0BU61STXVt0d/T19gNc7cjgq6ZQ1tJtVHHEIS4dD88xR56T7sW9T7Jgd02/TTY/nC4tuKR7nXVz80c2xN8MzMl5uQGOgB01K3QTTRRXky3a3zcLUsxdzNndW6Eg3/UWCyKtsfvMZbGs7b8cjKR5KAKvQs=,iv:lxOm4rH267CIUoQSoxVm0XbkLs8SkZhKS6pra8SQP8c=,tag:p+eZUO/hvw3yzGbzVCwz7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
