apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    EXTERNAL_DNS_UNIFI_HOST: ENC[AES256_GCM,data:gCREsrGNrEMH3d7LYNwdsQ==,iv:leiXLFuEgXsk6AKrRVIcukSRgAquvubBvE5qOSw/Qqs=,tag:cfh0/6Q1lkXoNe2iBSAkWg==,type:str]
    EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:uW60wpdtOh9gt1id9z0gNGdmkMJQGxISHpt9KNJSQDc=,iv:H/WHkEu0mKje4NtuEzOeE2wjTn9qODQ2YW5z/eqzjmU=,tag:B3o4ZP4Z0mvQS+usmuVGoQ==,type:str]
    EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:dCayHY4YDGTNU2MP49OP2RlcfavauDU0SMSjroHe7pGktQpgQzhhFfOar+A=,iv:v31gkXZrczraUlS/l4EBpRp+isjqSfTmewUtnecO4l8=,tag:O6sHFU8wO15RDwOPpIoWsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4blBtS2Rwdk5ML0grbSsv
            NEZ5TExzaTBYd3doOUIzRGI4b2FMQzg3bUJjCmdYQlFFNDhqVWN4OU5jbGQ4dXRG
            MkFvOFE3UWMrRE5mSWFzRjNjUHpqcW8KLS0tIGpQRFJHcEVEQ1pHc2hOVzczWGxv
            eWVIZW00bFhXdDR5aWxBMW9EZS9nNHMKkeQBN8hSsevvpQZrVVZdwyV4GeSWr4pX
            Ecl9MJgb6Wz8QUKnPzD6RD4b8HtNW+gPYPSzl40UR18LRQ4gMwzT/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T18:44:57Z"
    mac: ENC[AES256_GCM,data:EA10+ynHjJvsTKcp381u+iT2Key0SAyzeOb7sFUyGZ2dQUAwN6a0AMP1NZIJ7UNR1xgjlFhoskCsKChtU4oCgaKKfL/pWfUAXssjwGGBSRE78Leo3N2ZovvRsG0731AUvcEM68YJ9xD5PdToB0ZfePKHWkF2EM11VqiVUNBFOhQ=,iv:n41ZFZ6LaWKjH+qlfTask5q7mc+p0iSCZfr7LB1PcSY=,tag:JP8hPAOoz9/+jnvr0TLNTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
