apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:5BjKldC7GyFixPOP76mhardAd5zSsGIr6y9hZmIuq6IYWfAbgzuqZA==,iv:JFLLuuhMOdkhCp6+jddTzcronRG1dpnKoaU2aovf5bI=,tag:mZrK6sqO1bTbmYhvnC3vgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV0NxdkZkSXNONytadlFL
            NFBnYkZTUHFCYTVDQWZsVVh6QTFuNjdUUUZJCkFDM09GcFNqalNhdFFjdFV6aW1q
            bVU0cGhiQVVGVjAyQXlQaHhvai9wMHcKLS0tIFlwSlc4Um5IR2tuS0RoWHh3TzZ4
            VDdFNkZ6NUw1dXNyaVUyc2JtZWhzd28KuSwZjuR8OpL0v6jhMnZaMLDdqR5sksSt
            vW2w4xcltEsYeOII95fztkpz7eN9+L7zYBp62pfBk+F5vunj5vsM1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T18:44:57Z"
    mac: ENC[AES256_GCM,data:ApRIzeUMUd98nc6xFtTcXISI9UrVdBxjp8XA9T5jesHtGwHbYjCY80cdARqDptcNlYI3564eMerWGcDaMCNkzTrPA8lAygwL7m03H3VgzOXwnAsMdwvBSiKBbXLYjBg3+HrioI/L0dxKiyH/zW2hzekYu9I2YNa+O2TL9BzT8eI=,iv:rtgClQDGzOieB/JWD035rMteLf5dcmoeN8lyOAbSpLI=,tag:f2okOcJ2tdNSUoeadhMThA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
