---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bookboss-secret
    creationPolicy: Owner
    template:
      data:
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .bookboss_encryption_secret }}"
        BOOKBOSS__METADATA__HARDCOVER_API_TOKEN: "{{ .hardcover_api_token }}"
        BOOKBOSS__OIDC__DISCOVERY_URL: "{{ .OUATH_DISCOVERY_URL }}"
        BOOKBOSS__OIDC__CLIENT_ID: "bookboss"
        BOOKBOSS__OIDC__CLIENT_SECRET: "{{ .OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: bookboss
    - extract:
        key: hardcover
