---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bookboss-secret
    creationPolicy: Owner
    template:
      data:
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .BOOKBOSS_ENCRYPTION_SECRET }}"
        BOOKBOSS__METADATA__HARDCOVER_API_TOKEN: "{{ .HARDCOVER_API_TOKEN }}"
  dataFrom:
    - extract:
        key: bookboss
    - extract:
        key: hardcover
