apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ioY6EYezqj6H7h6d6oy+pKdPWyLtGNhP6ZMWGoPFGK5WLb44,iv:yM0Mf7EmNhGsDnuIUlyh2WeVwfa4hwKdv/uY1egmyxQ=,tag:vbeBiUuGyHjMd3UdLzgIvg==,type:str]
    credentials.json: ENC[AES256_GCM,data:rRdQoQrgSQ9l7fvGN2Zmuzc8ba5nCwSiQhAqfvquRpGT+Bxe95hU2xfgt6UEUPBzq0RDq/Yp2al3myiTkhDWQhKYXtDbYAQ8mZyxigXhn8ropUGovcGoiY4cEin2jthlMThaMvWWshIqJaDAA3VTr9GH9fMNl5yUy9CxxuO+9vzp44LEmBv/VC4pmodrGTq8/AQKPR/jgS5BdCzGEtIca93gjzlgwp64d/yNoz9ciA==,iv:IeViXFXjllzpK7yNRGvb2SKf7uby82/BhRubiimcT0Q=,tag:fk55A8GJe7utILJeXdSmww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQkNKSXVwNmZ0dFQwTkNE
            SDMwbzMrbHc1OGVkZG1LbnpXZlVGY05maEJnCkhjU0Zub0huRWZxSVZhcU4wQ0tQ
            eSsyVzlWbmZraHY1Y2J2UUZOUENldmsKLS0tIGQyV3NFMkphVUZVTTdvZ0FsVW9V
            OSs5endkT0l4d05EbjFXenlzZ0FVUEkK6cHbFVql1e+KFqmss0Te8Pr1DHJx+z2D
            i87P39WX8w37fuGTqdMxA6brNd9Sz8phxh+h8sKHUTMyfofUx5LpQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-23T15:50:56Z"
    mac: ENC[AES256_GCM,data:hptBcEsCDnHd5OAPH/hR46iezdQUhxpHtCmNw9Uf46if60r2JBHJVr91n08U2OJTpSm4HIA6bjf96dFfZfHOWLTfQHjtoOVTintykUh1YNsxwAiqpOpCFmJ0JY8Yocmjjhqhka/Pi3WiIkwxjNZ1J0upOKFxgZGCTf8wcozOhVg=,iv:hRcIiXiCigLY1OBrIfKhqJSOvo7ca6jOKHep+a2WFRg=,tag:67xrvDSCvW5WqW9/a2NgjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
