apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/e7jE5dSvwnoYTTu1/BwNjlB0vLIwSzBU3YmwXiwwngxc7ia,iv:7QMnJoJ/n1Xxw0yopizSEspODoFAfYC+EziCf3ddZnE=,tag:YJrw7qao3oBao9l2CTcNWQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:Lm33SIzrz2EwGrSvQG+YAii/MWjxM3GINdiM+wHILBiqbKiwgTD3gi9WKrRx58BF2SYMGruzpnskYOt1ve+UQCSJV3iu419s1qYGz+jDNvKgaMBFoDlMvJnWbd4YnzeT3Lcm+RjLyEQwinMKBdwbPssj+V/pAJfiEUgUuogSBeILHlvL3KHdMa+GkSaX4uZOM6w1UcQysdUI2zxo4KemehQJsI4nrHq2x7ZxeVnMBA==,iv:1XTFCq0PfoBIjujuuqwE9kSBUVuWQghUBiePNP7eM0c=,tag:u0GP47fOG/F+PgGIGrPVZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMVhYdEUySjlNUHRaeGtE
            dlFmWXpZM3Q3Tjl0SlM0anlNM2xscjNEVXprClBCU0toTnNvdkp4UHVkZjhsZ2hL
            U2VmS3dhbWEvRmhLcDVzVjVqS0Z1N3cKLS0tIEM2VUh3S2FBWndrZWtudEpLWUR2
            dG1HU1owajgydm5KZWxOMDRDbkk4dncKMLCQrI9FuNJNC30b4++SIaPow5XwPmMX
            wc+THofT2JmNbzcB5U8UE4GlHtUQ6aqAH3Jj2FqRW66S3BxocMugLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-20T13:45:49Z"
    mac: ENC[AES256_GCM,data:ZDoPnq1i/z16+WD4ov3HgQiMThl3cjj601/H9x4hi45ohBl6CXoQU8KbZ7yySDcub0Q5vfH+VcPqyObhAjIn4rTAEvrFqA+xpt7JlZbAu3xrJLmWLcz3PqotSeGPYG/GThrsmZ1s46x/D2ui7+Hbu6dUq5j4n7/mGq/2tGPYOsI=,iv:DNB27xoUUN9opAxcSmRfPw7PTk6xe8/8JXtYMo08MVI=,tag:qh+AbbXDZgPmaJnbubiV1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
