apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ANx8AWiTj1TUinDIRpkApNck9JmcSTID1+WFilVP4cLy3a00,iv:2L3I0E/LYE7KelY34cPAsVeNg3vjBZYBaxsLJ+0EpTo=,tag:EyaJKDiQEcFgIQNU5fy1Rg==,type:str]
    credentials.json: ENC[AES256_GCM,data:oQsmMGle0WDKRqbne7tKpyvaFjwPv7p7eZdcJIuHwNDqbnkay/lCsoL8kmQaz5zipcOFAH1kmLpMmFMDECKJxPuCVAYyzIcdt8TRXxUGExYWl6KT4jBvz5kzooqeWTSYQwZCpnDd4Sh0HSF4qFGMwBxNA7wyvytj3FbFja81L6keYFV1rh6BzPmfW9PdQB9Q7xrkoS72wIyRXSSkZQXrvFwcvcUjLJHHrdyr5Bd71A==,iv:UK71SG8McoLwqqRbb7ml9g9Muq3T5XYHOzJTdf+dpng=,tag:wel5AAOMwZllS5EjvgJm5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZExUVTBEckhBY1JVSGo5
            L01yRnFyd1R1cXJWL2xLUEVTYmo4S3c3Nkc0CnFieTZHSmYxTzM5RUdteUt6dW9q
            UWlveTUyeXNXT0tXRTU1amhSNVNROFUKLS0tIERKV29aNWtMRDN2TWNPTjY4Y1pB
            N3dwVGtlZkxJQjFDZlA3eVdBS01KdTAKo78K6cOxX5+X2573efzD8SB/AK4TgGpO
            go21SXLovtpAZoGj7mEJ7shro0E3vWnbRAIAV1LENBK7UQ3nUEzd3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T15:31:41Z"
    mac: ENC[AES256_GCM,data:k13F27r9mzsqxS7tmRoTBk1b2HYI02XrVM3ovoTI5PBjzqBSK2BuD+UlyX8pdNUhRXLrRa49TYypJHg2dAnAOFmB/D83/w1A38q4906CbAF44OaomBnUkZI1T5FD+VVnRnDW+3m1jrM+48xF5pl0oClsXLriw52nQARo4hBGxw8=,iv:92eS3o63ccgR09lY19q9NyVh3G6R7x012qmc/RC2JqA=,tag:Obhl3AfYPAR1cxf3M/tlfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
