apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:RIRiXv6Tx9fV/hfTIFjdDzxgQF9c+3khgIS+DjnRTcg=,iv:WUP2fzRU0OSowxS99KCbziEbGLS1wKEq84iAAypK5Gg=,tag:MIpd+eAse7sbx6l9fgn+Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTkZUVGlvdUNSWGExWUU1
            RXhNSmI2cDNmWnBUVnpUNXM2OHNPZ2Q0d0h3CkZ2bnlLQ3pXNXR3RHR4SndRR043
            Wk02Vy8vQnFnMkdyNWphejI2d1Q5ZlUKLS0tIGxrbGZlaUUzYmMrRmF6WXlJOW56
            Q3dRWmFvc0QxMVN6NVQrcXBmMHRBRmcKMZRukfEk/WlIG3e8nD/xZdzbSlE+xDub
            J8RPDcOKVFiT4bNzbRZF6557dsxFE2bzuJrpi8vg/7K+Ffdoqm57/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T17:32:34Z"
    mac: ENC[AES256_GCM,data:qfwko7Wt9LkM9AQ/Rcsz/0PF5y9hSQoy42aSfmUu+CpUx4hGt76aMHn9VQvE0Wrxl7f7TzklrHYTZOlaJvcGGYc865//q1m3qLu9fFL+XxJlrgEkXYu0+PEUZOVXnaKLAYF0IGkbP3K6CTYzRVpwLLVq3iBEYyZqjkq0iNfWyBQ=,iv:ytljUrDEoa0FnaUjweHJvvIOpnCNo/FESZ0gbAokZuM=,tag:REaQIIIWRW3+fnJv5rqF1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
