apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WghXFa6W3kyyXyiJwLHRA/PaQvaQ+DFS,iv:IVqLQ4Sk3jzRa4TDDz5AR7wOej8FNPckYr4E52uMkAI=,tag:GEGO+hKkzlIIgqkvzPX4iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs4yny0mulfz0rsaswzx4xwtk9k455j37wtytsg5c3796t082yfqvpgu9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZWFPaExtODFkZEdXcmlx
            a2l2ZVZJZ3ZFMUZUdFI0K0gzSWp4QTBDMVRJCkNNODhSbkRjODlNb3lzMmRBeXVy
            UXovY0JjQnpSZGpNOXdQQWszSzluQzAKLS0tIGd5YWJST1pGTkRoSXlRdXNxWXhl
            VkphWi9HclRyVGhkS3B1cHBMMHZLbzQKGO9qxR5m+tnRVU1dEh69IGlggtUUeqeT
            O1zM7OKxQKyW130Qf7LoS0CgclAoBPzl2NKaHZbvprh3dgZZNFqQhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T17:37:32Z"
    mac: ENC[AES256_GCM,data:xNYh1JOQA9EgKoauKgFMrw3PQnRA+oH8rcgOvoCvCC2yhmtJdzIiBDZvjTLNcUNQ8dEbyuLX86g8NKaGrwseFt1AcDX5E4OSJgXuVkJoHYTz+2ttMJflQOu7AWtV+1AL2xdn9B4B1reYN9yHQM4fu+ZlkWwAMj/tnum/dMUI70Y=,iv:HiIa6dbK72XwC3Yz+BFHcdNjkq56yNNqdkKexRSnGwg=,tag:MRtSIbTQZwF/8N6DF+zEbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
