apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:46l37PjJrdJ5cMrgSWvJ/zI1L46T9jr43rRa79DoolrVMvmRAu6yFg==,iv:DvdcJJg37tiHSrl7XzKEymLyO465nfxKv7ZuNsJiCe8=,tag:pNWdVH1mFJP/TS5AgLwjdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRmNlNnI0WDBTbDZBekhs
            S0hEZ1p3SXNHR3JQSXE0SE5WOGNYZ0tJUVJZClJCUTNFa09oS0lsL2FKL2ZTby9X
            bjVHVThrU3lHK0JrRm5zREpZRGdWQ0EKLS0tIFNDL3dzTDhEcGVTTCt6bHJyMmpW
            R1N4RERLZTJ2aXpGTWR5N2RZUWgwdEkKI/myseVcxH35kzzkAqVMTYlNLblCYmVE
            3KrUiT/sLDLLwC/0bdKCyooopS+6kpdX+qK7uNKPVjw6SER2Xa3kwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T15:09:37Z"
    mac: ENC[AES256_GCM,data:nbbDQ/2JVY/z3AhCRsqfuFlTus4c2xwmne+Xsa/4+f/4wpdcjjGfJ37s6Xu9nTexxu3sKnQjU8mBuDaBGtEbQsX7e7a5evyGrKftkzb3oxg3pwUhH6B0oXF7H5Uq5AsZcnNbCgAS83DFS28GfTHn9lvsc4+Nx8+f5A9havQF734=,iv:eOJdcLN/7GA1twjELPsAojRo1Cc0Qn/9/yspuONH7Qg=,tag:nzDeCzp77yIfQjUnD53qMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
