apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:w3JCcrjmLNANn+At1XYw1RAkbFQDdyrtuWw6FsLUUJ78HvrV5teDNg==,iv:xqhaGayOrlclW7ek7xPRsU+siEeLgHY7IjxfS4zxetI=,tag:Hq64aiUuWMLfLH5zmvr3kQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZE14LzE1cHhqZk42dXpT
            bzBtbFU4TmgrWFdGd3FFaVd0d0JDUXBHK0JBCkJETGNSNzZFbTZUSitjajNEL3U3
            UEt3NTBJVVhKUi9EeEtSK2RFalpTVm8KLS0tIFdUbDcvcE11QVdCNUtNQi9sZWtI
            SWJDZm83cGFhdko0Q0IvTnBiM2VwV2sKEAn717UrZJbFF66O3dh/WL4ryBpb8A64
            c+zjEecp/Bu3z1jSLHx2/WvheybqnQsYfA6rVk+aAekAIaXU4/9vVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-23T16:15:11Z"
    mac: ENC[AES256_GCM,data:C3tElYaX6WQ5hvf4JpA9eY1zQe7c/IcqLTHpPQTCXYKIFm1zQpxLGpSgqLXtnv7NTMrUz8hXCJThTYqw7fJQlqsVhp40cqqTsh8wXZQQM8UqsTDUMeYhJOvGuP1JoAiN9o46aNey7XWYQjFXBCbPhZv0q9VTDePBfDFTRmmIPHQ=,iv:+aWjRBlWANgVG3cLnMrEVHBQ+K149PP9KY1t1L26HZw=,tag:XxxRgp+FMIHLt8jkPo7sww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
