apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:SwYz8zO46lJqh0tPFELt9lXrGUgNmLljpz5zHftocq+aF6da+Q09wA==,iv:i1nATpIGhAHPuuGp4xXS8VQy/TBSeVwrtz92ZOr+f0Y=,tag:wmQ7thc+PNrMYbeu4Bs7wQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSGdwamUzVFoyUFk4VUNu
            WWVXMjZYbExSUUpPMlhpMyt1eVBKR3YzNXc0CmVmS3MwNUFPTVE4NEVPK3J5aE5q
            MlFHdXVLQTRwZ2l1M0dPQkdzRU05eEkKLS0tIEwzSDNrdzM2TTVnRW1EWXhIRGFO
            ckZvSG9POUpnYnYyQ2Mxd205ajRSejAKq2GK0G8xLL+znf9/KISf2RfCLJ2Fdz0J
            Y88OsUBKS2FwimL1rd7sa0uIfx0PrMuws9ANWvHPTMalANAtzgc6aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T17:32:34Z"
    mac: ENC[AES256_GCM,data:+H3EDu5uZcaBwpajbGTdvqVmU6aZHIdMj8jwTuCr7wZpGwUoBWyBzKFTsgKXj96I4ovhpOB8xlP6tF07mgiij98IsC0GLnlPmFTCb0GcnPetLJnZi5a91UC1mn8tIoO3CGwFO6/IVlXI4ZEqdNFex9mp8qEYOlQsbc36gikixRA=,iv:vPMnPonpurYGGDQHLj7QTe9l2YMnyAEgjw1xLYHM614=,tag:nZQIsQhSK0Pccz5KoN9LMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
