---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
metrics:
  - name: kubernetes_version
    query: kubernetes_build_info{service="kubernetes"}
    label: git_version
