---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wordpress
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      wordpress:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/rkoosaar/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: wordpress-secret
        containers:
          app:
            image:
              repository: wordpress
              tag: 6.6.2
            envFrom: *envFrom
            env:
              TZ: Europe/London
            #   PUID: "1026"
            #   PGID: "1000"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            # resources:
            #   requests:
            #     cpu: 15m
            #     memory: 324M
            #   limits:
            #     memory: 604M
    externalDatabase:
      database: ${WORDPRESS_DB_NAME}
      host: ${WORDPRESS_DB_HOST}
      port: ${WORDPRESS_DATABASE_PORT_NUMBER}
      user: ${WORDPRESS_DB_USER}
      password: ${WORDPRESS_DB_PASSWORD}
    mariadb:
      enabled: false
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    metrics:
      enabled: true
    persistence:
      config:
        existingClaim: *app
