# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
stringData:
    token: ENC[AES256_GCM,data:eIfmUAoX945t4zS8DxH9uql1Lz96ydu77dQfG4N8JkOFsBDYHfhXOjDKAmPiUHvJFuyOvyn/YI9DhrrX7vSZj6x+02IvC9Qj0buICoxbSFj/Iz05WDKKj2oiUWkvPv+3DDTJ6OzoakMt4ecoCi1IWdQrdbAV0CeZU9o6K1qyW1akSmx8rMHcEt0nNfnTY+hXfJbLLqZxM4voiRkFwyEbH1dcNh6/5kQdDCWQTAedv6Yj9Wm6WZEMJhni++cg2+S9mISDH226ZCC9w+qg9b3xtYYW+qGK6VYHIRZ3LugJ3+V9iR++hTksLvXCkh6JECLfoOGXW7DET5eT188rAx4a9kc0gdFBmt/GyXZgFY4qRM7qZjMFwW1dj7GrE9HPYEe/pKbSUkVp2clP/2uDR75pBROPZuKnFpCdZYznDhyw7a7jmETkizVFOk8QWZirhY0JiDV+YvS0cgaxwOoSzc00vX3uydE5pPNyGZu2ZDd0Qxc1exruI+XiT9JP4FFiBE6s6P77siZn5s2Fw3+LpAZSCGa5D5/OblZB0m0peXL93xG7pydpNU3rwVyCmB9rw6Qhpc4Vi7Z8YXobLnAblenspv7/HY0GbcsU9QZ5tSCqPoqcWRG9kg+E2H6c+ZF+Gg5YPTa1OD6o4lQ56wm4B28cUK6ODV4/nDtT1B4VksAGJKLPUjW4JH8fNvvnjdverJZXbrm1KHSUyKHhjzNdnlm8NzQxGUXKD8qEW+kkHGNOtavTU/4IqJH3SwTgHNreSIBVxyBNqbZyeo1noJR6m3lYQk4BsBg58ogusvglHWhs9Jyxw/Uj8B+5FDgkY/MCiu+nPg+NmMBBM9N+ZshN4j3PdLjW,iv:F317lJOXM9EmR2tSTU/EYbPHee8YpGtwq/v91aswHrs=,tag:qB7AIRG049Mati4Aqa4NVw==,type:str]
    1password-credentials.json: ENC[AES256_GCM,data:JfKuz3D+fcVYKDRm96RW0L0N9yr73Bn187IiXMWW3esF+s0bz8+itVN3mNNkY1UdisT10qe4MS5PjLqjCVtvnxaen7cfsL61w5dYR+6vq9nMC9vrFdwbxwhfakHQoDRGgJcrcPGMny5Mo3GdclCqYvvaFJR5/hlIqfwHF+jie1JyWl7zn/r0rKIiWP+jSQa0XHLrk3HxkGm24J91GvN5jvyKnWQwztTcySCX3iOLRtt7TD7MU+K86mSF1lyF3zhW7izkDu40YU+ZTU3FGIVMLKO7eRRdALHyvCsjkGMXGAVExIxaX0W2PTQqJnizQODTGQGPfIX5KNSxWg4+nrpqGOu9lGThT4ufpklsBc+bn15zp2WEmYlrNGVg+p4Vo5NBhPbeQbm5ojOHgGfHiWZj8ApzJqDc/IoYI5iV4Gijw5tQs5IxuRlv1JPf5c0XlNn80Z3o+6kbIeMt3/uQFYD1qXPZ0PX8D/hvs5doiXrfJaZonHe+1Fcy5/deXShJrxSJCm19IzpyAGyIFSsewss+4PIVv0E/SjScx8ADE0iPW6JUDpNdM8foRDLHSUBvjkecI+LxbtZJgSzBt6/IwFkAvWjcnS70Og6O/ZuHg0fD3pdQqvU/f0nQgx52Sx7/wsgIROzXMn8LgZ1lZ630iZ8QPWhSyChxoHz4pQxlUuKis+dVHkvyfHR84TX5N/21VzeHH3e1/Lu1LtQnS0lt71BIxbWhvECDi4mOBIsERZzHAxuasNLCq4yRV93VAYrB2hhaq/pYt8bZajA9Xp/lXf2tgeV3E1l/b7mydO59UroxegP3CBuNnIVAWD2WJEK13uVdnvHRA0gnLN1eejwBBJGafZFl,iv:V1gKa4I8ssSFOFz7cR/etc+/y3XkqdUsi5D0EkzlGc4=,tag:oIVH3Vi06pVgTAalo7mlyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WExkbmd3YlR2ZlB3N2NX
            ZElPMWM4S1c1T1c1U1l0L1AvMTllUngzRTA0ClpSaUxiaXdWaVpFYmZVZzBOSVlU
            eUR2WWd6ZldNZkplZXpFbWt1Z1dFVTgKLS0tIFd5azdlc3F5cjMxWjNoRUV0d2ZN
            SFFDOFhHbk1vWE1KWDlFRHdPNzNoNXcKdUInGqgU8YJnZ53NXGgg2H4PEvxPKhqo
            +sIXw0798GRZKdh6TbhstFSjLxs9sF12MnDxiH9vVEt1aZxex0xL3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T12:48:47Z"
    mac: ENC[AES256_GCM,data:tvefY+nZoA1iWuRcFvBwMjofl5/ugLez3cvoXTHnHtKpbw3LLzqiALzUiQ9g4OmHwnxyDBfhk8tMOZ+mJ/5Iq6mUhbiai5UasjP1ElF6J+4DKZXL0gYr2Kd2AmcvYNIUQbCEEBmqH3I3g+GSVkDodwAbre4MFvoU9PRx3NCwFUg=,iv:H7ns45Bh8WwGmRoE8x9/DbKLRPS7+pOd/gOZhFn9/Tw=,tag:Ay689YLQbZGrxvRqrvDHxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
