---
# yaml-language-server: $schema=https://my-kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-secret
    template:
      data:
        GITHUB_COM_TOKEN: "{{ .GITHUB_COM_TOKEN }}"
        GITHUB_COM_USER: "{{ .RENOVATE_GIT_PRIVATE_KEY }}"
        RENOVATE_TOKEN: "{{ .RENOVATE_TOKEN }}"
  dataFrom:
    - extract:
        key: renovate-forgejo
