apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:j+VA3+inG2aTaa79k4a2wY3sPOLwjDO/kP4zG9T05yIxpxWNtuqjRA==,iv:cjF5KZEZ2gO/BuhsHNTAfDX3pfrM+cSfZnhqI4ucosw=,tag:Mj6Z51TtUOSVjle8P0rFIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZTFtOC8wMmZyaVgxVUVX
            bGdsbDY4RHNXUTB3VlNVdTYyWXF2K2VoS2h3ClhRdlVNOVIyNnhNVUZSRTdOQVlG
            dEdTUEExTk9mZENhY2VSMzI5ZiswSTQKLS0tIEdKZTZ5aXFoL0JhcGZmT1hvL0Zq
            UU82SGdiazhPZFpHN1NmdkMwV2VzSjQK9UJzOOmrkwocdhis3xmVlbZ3mZV4uC45
            Q4Oli3EwGfhlJiCB939O3h92r9HYT34B5jImNoReA7kg9Wrris2nPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T21:25:49Z"
    mac: ENC[AES256_GCM,data:7EYbpEf1lnc/7Htcsk8h1wu9txWjk5GgG3UHiPuu3mO4F2IoNU30+zo4ff12pVDZlz+KC5a9lO4nM7tgnbXF3YIG+beNoBfWbUGZGrn/fC5LWTT4qQHMpukUGWPc1I0xLUDoIetlCkCDlMCnLJaqjM8BbMug2neJoCDDx2Vy0es=,iv:8RAZyJ2Ump/QjFqJThLxPU+uruipqx8+++imMTWgrTc=,tag:ZmOY3jiEnwEp3ecLYnEgrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
