apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:I5q5vh7fW0GAuwX0Y4k2xG72MgTOR6QkaVNMZkIA5G8pfgc5f4vYyw==,iv:YEiQc5WuQbZRx/fXXjUZrmTVzgChmBVaIBl0KOtASNc=,tag:B5ZSCCwFQpXBSQVMtnY4Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdFdET3pON3J1Ny8vM1lp
            SlRwQ25rMndoM1p0emFxeGxNaGNLKzZtNGpRCmJ0WFV4Rk5vbHRQT0xCUzNVdUpv
            aTZ1T0pIcEFNNzZ5bElmZ00rZ1VwbUUKLS0tIDZGL0pPR2wvamJPaGhXK09icC9q
            S2I0RkY5RG04eXk5endHektSV3BXK28KU/0zT1wS1hf66vVONGwKucAqLSOJFXwF
            7qz//3AYEI4NkvGZnRv63j2awWWvk7S4JY8M6nepYBMo+tw4JEazMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-20T13:45:49Z"
    mac: ENC[AES256_GCM,data:i6L1CWYoCxr+NpwMWI3cTriy4owHJfo3ZVCQPH695sKBWufWFoFVzw9dtM8jeBzMBqvAYVCD2ykDTHAl95nb9pR8qO2cGKx5h3ad6MhJeX2YlN+WRwfe/CXIlBNvAJD2kqbw86u8s1a0HD6qpRDIZG+A9eQjKWcjuhlOEGZrudQ=,iv:uQjUbo2CAPNH1yO+S5Mnjo6URqnbrw9BIQlTy2tlKzA=,tag:UpWhxBzvNslRzcVnY1MFNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
