apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:FxjRVPeLpj9jj04dcwci2tBZtMBippfq0iIInKk3yuX1jmPnnmhIfg==,iv:vi++YaYY4rhKoUgHjdPfY/fjX2SLEgpibpYuuU+gPD0=,tag:1fGK2EyBsbkQoCXJQNr/Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycVF6OGNXWFllaGhJT3Fn
            cDkrUXRYdE44eWk2VzQ2TDJhWTE4TkZyNWdNCnBVNmR2NXIzM0xmR3QwMDBuN01t
            WFJ3TkhhcXR6dEdkZTJEU05sMFhzQ2MKLS0tIDROVFhhZkRqOUFVbDFPL2ZwT1NC
            VXRWb0RxQnBqb1FPMTlhdlVQOFpCWWcKF1NpFLopsFoTQkXpSKQvDnMQq2qMgqCU
            ccaNm3INi7roD41hZrUzluziwLaZ7sysg3zTrDyjSYncmK0YwOx0ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-23T16:15:11Z"
    mac: ENC[AES256_GCM,data:xH99KRCWbYV96u9evXKKZcjIpcIOgd0yC01PsBvgKjBbv4gFWif2T7DpoqJdjqOc5aJR7/PN00T3rC4RLFFdVgdpVZqj8CdcEPNiUFfV51Sf7gwZlUEer5LPzCcBRHlwNV/rgaQIEhqMt8QKWdiXXloutAvoJJVAeUxXkJHF+DE=,iv:32/pKUHN6o9A+N/MzxoYMZr/Es6OXvf4noJtGNtH9Ak=,tag:75Yum0cmHVlU6+7dmQHBeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
