apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:ReJPlN2xGIbuT6xhjuXhWMy1KicVelA5FNPr+t+WLoqe1oLK61Zhbg==,iv:H4LL2ckRX7C5TQXlaoozPjEYi6w0be46RRFmqFLFXho=,tag:t5pERfG+Zwa8AAo8yIFeIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs4yny0mulfz0rsaswzx4xwtk9k455j37wtytsg5c3796t082yfqvpgu9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUElnREhCS0x0THZiWFpZ
            RFZwM0hMekYwamlPNlRsc1NZUm1UNktMREJBCndsOFJkWDBqbm0zQXZPZVlONXhs
            cENEZTFLN0NIZm1LZ1ZiaGNQZ00zMUUKLS0tIFBaUFdPZFNqQTNqSitTWmFnRVJq
            MENlcnVZOXdxc3dhRGljZDh6L2h0OUEKvFZMRS0HKUfJNlv1VMxav2rKJ2h57Md5
            fH/qQ0LLu6xjOPUJUz4nxFds26Z/7MbqciOYTjkRh2bvZun6EgXx5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T17:37:32Z"
    mac: ENC[AES256_GCM,data:PWWAy8FYPtXzSLiA9Ys/Fv4jccrHmzk2wnleYdDb1UOjC6btcO3vjD6VT2mmNjgLR185fTzaWR2FTL4oIKzLgA5b8ik2I9MRjYeIz9pT0yiw15pp5Bj3ZoqNrJTEYtvKX9aEIDELvxJEJ8ZBfW1++sGYXciOgcOHf90f1Os4nA8=,iv:q9DzbQs6wEwA0QckRaNT5zC59T+DCr3fD+TaJAMQmNw=,tag:Q5qxZxKol1ppJT0wIodiaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
