apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:rS0qdnTZcXdBW/KyfjAlF84nR8cdE1uG3yYIyQOqpUShufMYEBRTkw==,iv:+xAa9XtnWahsksn4B4BBx2UMBa2BPaeeRQQ0166HPIE=,tag:a6l6oxFHdnUC2+MkcupSkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRVRUUjNlbURERDBHY1RP
            TXNheVJMek9MOTl4dVdWMmhkZXAzaGIzcG04CmhxUWs5bFYwS2E0WmUyUFZIaEJk
            dE8yOU5XaEZBdXpWMlVTa0hNdGlFY2cKLS0tIDY1dlFBQkFCc052Y1pSMjNHSTRT
            OVBQemw2NWdxMWJDQll3d0xVYnVPdTQK7d1WJ9jqPhQpIVbot+vkuVloxIlMGhcp
            mNqepB6DU3D8XxhcCptIV/URMf6RbB5woNLusQoMfxL7EsXQ5gdFgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T19:42:08Z"
    mac: ENC[AES256_GCM,data:FC5C7xgEfbUYTLpXtTDUx4ozRgKe7foZMVehHnsdqqbqWeGw1IUSnWp1OaVUQwe3uK3LphPGOPtcOw+8Ofr1+FgjCOi7VG2nInSyMd89LMQD/9rmLEcIVzBN/OxNrO2VP3R4/Tkir7cPIUO6S7LVtPpSRxLMdl86V1uWHPMqMCo=,iv:pIqxgQzMDdQJEITK8zy5YSfBwRl1tgGOhIemdB6jHaM=,tag:0dmU175Fjgnuuux37UN10A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
