apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:YINZ53sabJJQC/qSPNSQ3nCVNVbX5pfbIgViHmXc2JC/h6pzk9VTpA==,iv:2nvd7cYF+0R3vqmUH5PAlFYjJSyKdVAUGjav+xq7ev4=,tag:wQOcElWECjn5YNYVxDlf7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb2Y2NHpiTFg5alVKeDhP
            QWtaTVVOSnN4a0xBZGMrczAxelMzeHNNb2k0CjA3M2k5SnFkZEZZSTU5QXFpaEhW
            K2pIbUFMUkVvazVGUE9DRERiRzd5MzgKLS0tIEdpWDhudmVuQkw0NUtZYnd3c3Ft
            QnJwUXZHbWF6SnJiVmNzMXFJdmxSYTAKyRKljgO0hHHbSPoJdkVr7nqyhrizITvE
            Qm+yAQAAp+uBDlS+3y3mFQutT+NIvMOrzmXwaq6mGddxxMBcI4uw/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T19:32:32Z"
    mac: ENC[AES256_GCM,data:T9GsGPtLDnEZR4WqKjZewYnkPGl5/GN89FKU254GYeOYQcDZ2qDoT0cMiyFNmP55kBfrnhQvDDcoW8c6lb912KWvin5gw/bdsW5PVKvkGg5NqSc8x23KzX+D1zSviUWZ4FCudTuGK+707mO8gVjO2VFoyl0MsFNby1cg4Fx2UpY=,iv:BeAmQlT6XmUjzZdLKWQM/8w/e08Ai0yppeNCnB/wrVY=,tag:2gV1SfSbnwdINrk5GDLjUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
