apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:B0FApbshj6kZ+ix+/XyGpdpgmm+Q0yV9hybNVfFYMECFS1AMRDrNTQ==,iv:EZU2W9HU1SMw5i+TG66UFKTvL3d2C80KGM0s00o2nvY=,tag:YdzQtyn8KKp+sSf+JSSm1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbDNveE9GcVl6ZGUvb3Y1
            U1FuU045VWtKWTRQK3FndFhKWlpWRHpyekZRCmF5TjBXNG0vZmFhZ0Z3REVCdUha
            YzhzRnpnMzRZOVQzakxwQzZRQzZhS2sKLS0tIDU4K015VmxadHg4QUdEWmlnRmxz
            bGlFUkdyUUZyREp1UDNYbFZHR1ZhWEkKKB0ag6ldxbYAd9NZ7xg0lTJly0tmf/Cv
            qCix0NjeuvqtoxjJQMyHFQx5LXevY0BiRhW82e0MvN+Ou+YY4Bs+kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-30T09:40:21Z"
    mac: ENC[AES256_GCM,data:hujtAax55NALkkFxC/KG1LYH+oSKdF4emeIYfgEizazU62ouBwQcyni0RPhfDpiprCKPsFrn3ZBlX4AV4+1xD6j81uEErmFt9T0qmgWk4PJn7yd53kO4/i1elwFK+Nlr2h/MNrMPtdow11HabPBRZzgiK79GJ7cRjjyEF87sw68=,iv:EC9qGuWDVS7gphoqsLBqBdGr93Cq6LEnIH0v9LW3WOs=,tag:MG1w7oKsMdZe1quCERaJQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
