apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:zVNX9WBhWJmu3Xt3QF621V6GwvQ6M3q3P1TqhXXL7qo=,iv:SrnWXLm+WVIshAnvjS7YSXtS5qSAQBQMADO1PJz9iWI=,tag:6bvqIF2HMtyhP3CQx431Dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z2FZNCtpRnB1SXR5Rytx
            S0dFcVVYWUFtT2o5N1B2d2xJcTgzUXJwYW0wCm92L2ZOMW9PNWtXUE9ON21YRStG
            S1hkcGpIZStzdlM3b084aW1xQUJWQWcKLS0tIDE0cy8yS1oyRUYvR1NvcE1mZjl2
            M3NOa0J1QTArSXZ1RUJxNnlJUmsxa0UKWnY6fLGT6sEW4xv6BJAgF4nRdopWmT1F
            jQBIOl+T/bbW189KP5MifXQlsQhS+qm2RDP00w5yQX7ybE40ccSj1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T21:01:11Z"
    mac: ENC[AES256_GCM,data:W+6bNTeCiCfxSZfBbL7gkzyjkjIERUUXyfbS3qMTDL/XXlq3CY21zH7y9Uv7i+TesS63gDZ72tvmOPQ9WSxNAMLWg5c8pnqRAKET5RBKqkgLNR8H07/06Y9/pUHaMnEan89xaMnFUm2WWJY7fu89kTPBM8iKu3as6EJG2vpceTw=,iv:MGDdYOwdW922fCDIkXlbNNa73nei1kWLklUjcNXK6Hc=,tag:TK2D/3krX8oI+Ah5aR+FKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
