apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:XyKsz5Jwsmp1VHkTa9FhMh/SEL40Yvzy1fBoiGWD65MmJMyN6x64+g==,iv:uN+InG3y4cP6HXfu4AkmlAg9TVo2HNieJRlbTJZGA4g=,tag:2BhxpOPy4YIcOdYmlAWusg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR0IvWEJuc0VTZHBMZ3Vn
            M3VobllXTjBQc2I4aU9WUHo3VEdsaEhEUTFJClBzam5RcUY1WHFZUVlhTXROc1dD
            cDZ1MUJvNEdZWWxYNk1pcVVNcys3RjgKLS0tIHFXTWl3Tjc4bDJXYTVhWS9mUWZo
            ZE52OC91K2pnQjV1bk9rYks3U0s0S28KXYelv4qSPRRh5jM31SM/UOD0OFO5D1TS
            Gwo/OQvS1+/Tv0QwSW64Qnu5qX63k6cgcGNj3tE7DODfGP1b59SVNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T19:32:32Z"
    mac: ENC[AES256_GCM,data:Cy3n/DWs6Qg5kZtgj9+mE/EVJfhnPBEXCyAwOffCA+uH7l/MBNPP5KJDl5TOvnrX+6Ll0ryK4BFT6PtolSx0DF9qk+gdtp+vF6f8s/3iRZb9TA4ggxCZ3vxA0MGbOvYsOqMBcUkHZ/x5/5AeP5X1Wr5aoCn/s+p24PCxSpJ1ZAs=,iv:GsvSp3Uxh27Sv1EOqFtHpgZBlDTGCZbsLUusoZdrovU=,tag:nToH6wWXLr5uKYpoPPgPiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
