---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuwunel
spec:
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
  components:
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/matrix/tuwunel/app
  postBuild:
    substitute:
      APP: tuwunel
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_PUID: "1000"
      VOLSYNC_PGID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: matrix
  wait: false
