apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:lp+nlWmuSCJlTDr4A/UuOTOY0/PnVmi2QfY/27lvE6m9QPgTHryvrRTb3h9VVajAB/1klh3c9BfE6LqXQZhiQ+ASRFoJTBITEFg+w4F3fsGYsZGKAqcQY2BggeoVua3eWpD1rV6nn2TvF3uhi+dPaYDwSmETW6Y54AU5ST1Tr8BOVFFzUuKkn77CK3DxjcFetiQBsppDLNzUxPXMCw+DeLkQEjrZE7SU9OOhMzO0VT9BmbV3kVlfZB1tVHWOL/sr+c4lL4WZr02gAcGCYg5lRT9tHAcoYSfNLLmLmOuN1RKTULorqgTsiE25zbndHc+YZWIKAfiuVJ/Nc3kq7X+SAs1pSEWU7hCxjFXSDC90aLHKFFusMkU93BDbyF4qo+Act+rt2AWV5ZghoiwKgR/7gUCcLcrn8iBJ1u/caQOEbuxTUxFzh1jQOCUj+QZgFHozJ04RzHfM3PKGfAsQe16NYuoZ5GQ/IWWgUequa671AvsAPHWj0I8Uij4P9Jv/nb6vLhZ/Y/OIwAX1bJWioK1xU6QYHXn7YvypZtrWz30mYb3gylWFJh3axqEgYD8SXlZv4EGhB1OBsufz7j8JkudaxnOrXTZF1/gTM4GuhxXvMjRVvJbkcPtJbSu9cMKsOLAevBc/5QVOE9d6Wy8opDx6TlDZJeLxsDsC7d1M7W+qMFhryrvfPQwTCbcld6Q6msPwQvPvrQ+J5Frv9lPZvs3ZJQ96HJq25igRcZZB1QMJFoAXSd2Na1k1v6SC9qtHV/dCLuXtWra7IFaAkelUDjZ3MeRLKJ09F2nf+De7rKjiOMxPF68l6NsiiN3cIlIvUXdopTywYzQJuhy6pMf6VXSh80Rd,iv:VCI06BJ1BgqVbLA8nDU5Mrf/VxhU+gvUqz67Zt32sEo=,tag:wYI9djlVNOfDa2a4NhBxwA==,type:str]
    token: ENC[AES256_GCM,data:QFtZR2YRR0KkwpK8t01RpnGHHfOuqJK+VqPRlAhaC45/R0VpJFqGAcxR0ksUthrUYrDBYRL355VaMZN6BJIdCEX/IZn9KlMIn1XE2CRsBenqZn24SY/k4GPlkMI1o4o/QBdqJeOEGjiBxPFgoaxMnSF2FC5m5RygWBxYTJB1qQncmefWhBbI2X7WTaUb/j8h4XMPsNdCg2Yu0mVp5j1bl975O3vD6Hu7aMuGnxmliOu/A5yuAJ7hW4GtgisFV66LlKDXn1UpEyFfDNAq7UcdJaJiCF9yrLZKu3sxiYLLmYRxCVpi4Xyz8NqZLs0/cNXsr5OpErKSrsSWC4TqyETy5mDzJotpAQKA+LOfb5wV7lp+/wl9xou9FIVsi5FqWvkl3L9pZz/gmxLRQUkWchehG66vZTtfNEY6JRdDr9CGlOqJBOlAlCJhVEiXqaksOfHGe0WVeMLTqk7lq8jAom1bES7EDynJKvqT5KHxNvaebQ6kY5WPEKlTqJyhNIfaPjDD1P9chUKS2rMZHLE17PRoqTWSIkcIZSKo/lpl4JEQ5iNSyT3FMEmtG6JpXxFR3mkmkVFVpN/p0BZs/UTYtiWUqKIWMUQmWU79tNBvo4/ZX/FR4/zfLN4jC92uQqdqWHosica+lqTDWJ14b+HrMWuxNBHkLrTxekBmlQ9n8Ka+1PNOhF+sUHEPZNpz6EawkNT95DVbSSgoHCGPPdOcejelVVbK+gkelwHIt94aotGgbjn2cKJ7lFx0l8zEXmsQBTZCV9w/qOC0LvJ8LAcu5U3sPvFQVgyOnXrjKUE+fxWZ/jm1KDn/DpGCMpdeyszE8/1Iw90fyByK4xPEVqDFT9SD1GLQ,iv:j+MZTqxQWTnFyN6nlgXpkt0Nk4K8igWxZiEMUKqgzYs=,tag:pciENZI5lFepk3Ln/2u8qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZHBhbzNmRlN4dEY2NHJy
            a2dtRW1aUWVZNXYxR0VScnVhOVdYTVZyQ0RzCjlpeTVqWGovZDczMHZhZUtMZWh5
            SGMwL2F3RkJ1SHBCd08xQjNCRTRMbVUKLS0tIEU5emJyS2ZxR2NGSXN6MjNMNzlh
            ZHNyaGdLanJaR0xEd3A5UTQybm0xdzAK1wKlojMPesufNLjg++lRNH2KWyGNZM0X
            4fsMuYx/eOQCg9D5SjA2hgkBTCo0j8cPiPNZVV29E5HhotqRfcHYEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T12:37:45Z"
    mac: ENC[AES256_GCM,data:nUGku4phVGkzmJt5ZJsbyWMMIzVeRPeNeTwDAj+oaI7FEz56bTVoDCoyc1wiofqs/on4Hz28syaiILqDi5Eov+9MLkqBObN6fqqo4x2r+5JA7klZ/1zcmKo/6QU4oQQ+97i4oO2D2VZAJKI+ELrRvXa6ORSHAyFtTHvu8iIXnms=,iv:tc7szT3rYXArEgn9tpOiSRbwgDu1oQGGum/7Xj4l0+c=,tag:S2eNS4SNtZSIMQoYg/arpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
