# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.jsonapiVersion: v1
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-credentials-secret
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:KSyx+krvfiReQ1EmpkxjhVoHCcEHtQT4Umi/c9TI+QkBwUw01uk+K+Zr0hbjEpt+DHPc1YOK+jQkOzfQuctbewqQhEpMqdO2OQwaIfgskKd8HWLOroivmeAlo14AtVDKb+NYHYlbSfip1X+exd/vIwJmjER94mL1lppw0piUB/SIQIXCnSEqDhqs+xa07yoFNAcHlYPHje7iZXex+3yfdOFacDByX/muyz4Y60saRQOcckjAJKLL656PBe1SOKAjj0q438pg/oH3N2w3wvMULOD6VvrGg3x9lwqlR1Th57JaQ9khZEj9R4+q4czjkWATaYKSrAUoZ5AEt8/cVgMU3TH116NVmnMkZFE+l5BHcjZkiGKgRAVlitIwQNJ7DUUCvDUzYEN1WwPJDMrQsMcKxKgEeqrPOBkNWBi7PI6BoqPRHy9cwFlFhJExMBCmGOa2llU+ZYCClVoDJrY36GEWDJd535uC7KCCldViH29rCsXvaX0JutD4PAXZnZwR7dwjqGgucif1qMAG15ZcJAomYyIVsYzMpoQs5ySclavXwNzN1gtZC4HgyL3dT+euCC8+fYgXyMTLsxlBIsmLClsNiMnXm1l78brXloiNskjO5oJWJpKyRIYIMaqDndQg1LAO8qjIK/VWE6H4lvZBvUE50UdN4GIqH5f8A0pCeSYB9G3RhtjSbD+CQATWXwALfJkjOgWZXBXIP5/3Q0bzRA+LUSZ1dk7L5O563+BTvZkffuB4Aj5JsETRdqSQYjMf4LzgwOZuyxgsNvby0D+Kh8ooPSTLxi3BE3I6VRZwDeLn5RJUM1yWVWgSy6494vQvpvp2NA1J3N4Np0U715A0uu0MkRXPkLupNZZIaVwqC8tte79+kKBr0IFJxJ3vNdQf16aRSVClvoFhsDWxmb2OY8e4+YsfUEfrs3gUZ5QFLuZ1EnXDsZDEpXgTAOqvYOvGcyoSLgD/iS5EgSqjPyvtQ8irwz7Hf2sY5Ao5KA27ySFG8RdKIc5B95yUKpfoH3NTgAv6xzTX1vF4odxdTxWxU94JJGhmzEIxsIIQlHaomSelG6APYLNXxGHGiQBWWhxldQ/c1CmboK6RfD/MpHzHnpg1hk8ZVELqtRq9WLeCIVIDUlVGpbryWw0SfqqUMdVoXCumEyZPKacfD5RaPcNSVPJ4ZCKYauvyo6hvPVecQ+6WQX8POzATBgXfJL1Dzvw7rEbgU0XNfvsbyZw/H0tX9v+ezIJ19sRxv18Qn1BeAIZfJqv4OxGh5Adm3yUdwJTYHRnkzk/0L/UuxS3wVGhANNGiJgqNP7+980A2Zl05vK9Pbm9T+eIw+kO1g7zS63HRTQF24X5DvO8bTWvVwvshrSHV6AsPqFwrq4/o1cY3u9PsqmH1RrAkT5G4H5wjUqeFqx5wd9wnU1I21quu1NxD6BluGLahVhHDjF53fAqTyZiJkxUrma9i09haZlSOpurTTFJSsBvUTcIAvIAPWcYQX0ztmQIFOpGG9TbaRTsGZyjQL/vXmIqMSCztqXkbsxpE/jMgU9gLQJl3YtXbsGFs1X4mCB6km99E5cGiVazjQXZ4+9yCIM6AQMy1BOnagHkp5R2pfHFaiS+bdvKFV68MveGkieXFN/018pSgC75qhdvisf9qQSIFmqEQqSVMr/OKdTWYCgcWieH5A6Um4t2XKMyWy+AXNgrjBW1HLv4gEZ/6qk9mHqtmaFRo87d1Tgai75TJser4MRStILqP5R4Mi22o14lm/qONg6UE1AkcfOnIoxda2j2yYHv7usVZE8I0ttwxTJ1OoR1oAB/nzJQCK5vR9NpiDYtYbLlWJebgdEpxbcDiPYHkn8J8+1/lYXz6Hc8niKOv892ShT1cL013icg3tQIA0fzFftNw4ORNJ2iis8uLrA+N36UlrrEdJgEgJAyU3HomDhh5N2IhzQ==,iv:dwE9iPgxn2R5HIp3LD/U4eb8qKHL82UZWUwCvaJn4Jw=,tag:5Cx03RA8baUw7SUTtiolkA==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZEFocDM4S0w3TmdsMjN4
        RktUTHNtYkxUNnVDSm9GU3lMRXdMN25kZ2djClh5Ky9HUkFjNnRrWEdKdHFldDNY
        eUtEUVRJcmhwQmZ5WWdaZ2U0bFdMV28KLS0tIFRnR2JZdzNrU3BZVTlHcFp1aDgy
        cXNWdnphbXJuWlE4OS9sdXQ3UGhjL00Kx6Vj8p/skO5qujuuUvAaE8pwQxjYPBTc
        kCkY38Ao3AxWN3YKbWYR4hhPnrPrXwFZ+StKv1/pO9oAfE73WzGB8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T17:58:57Z"
  mac: ENC[AES256_GCM,data:o4cFHA1MohjzpNgxWaRTb15HRLOBZM19TXN7UhZxc5aHrOPzj7tgIjdXGibgden0u7npsQHmWjcULh/l32izbZEamxFbGnn65AcJNjtQj301Vzyy/dopbBEuzqm1vHo+Wtq3qN0cTLDerLT26VyZbR9MLWV7sUrhB4F2eFHOIQA=,iv:PcvZBZrt167nrruMtC9Klwa2DHu/0xKlcKFo4Q/ZONM=,tag:mFxrNp+NOGHyydfsVFEQKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.jsonapiVersion: v1
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-vault-secret
stringData:
  token: ENC[AES256_GCM,data:7g2k/tZ5K/dgn56GsvPxw+uNxQ/DIl1PGDtB/3kgUIX8xjXIP/Nen92j8rBNCdoCTODKoOzcjoiuYklhDErReo77FkItuUhwmW408ftuAdrzgH3w1TvrGV/lDjwo2ksALw==,iv:yAGSOJsnVYGEy1rE49b4zfStHWcRmUwdS6mZzBX6rYw=,tag:VBmA79Pua3KLxxW7U5iRxw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZEFocDM4S0w3TmdsMjN4
        RktUTHNtYkxUNnVDSm9GU3lMRXdMN25kZ2djClh5Ky9HUkFjNnRrWEdKdHFldDNY
        eUtEUVRJcmhwQmZ5WWdaZ2U0bFdMV28KLS0tIFRnR2JZdzNrU3BZVTlHcFp1aDgy
        cXNWdnphbXJuWlE4OS9sdXQ3UGhjL00Kx6Vj8p/skO5qujuuUvAaE8pwQxjYPBTc
        kCkY38Ao3AxWN3YKbWYR4hhPnrPrXwFZ+StKv1/pO9oAfE73WzGB8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T17:58:57Z"
  mac: ENC[AES256_GCM,data:o4cFHA1MohjzpNgxWaRTb15HRLOBZM19TXN7UhZxc5aHrOPzj7tgIjdXGibgden0u7npsQHmWjcULh/l32izbZEamxFbGnn65AcJNjtQj301Vzyy/dopbBEuzqm1vHo+Wtq3qN0cTLDerLT26VyZbR9MLWV7sUrhB4F2eFHOIQA=,iv:PcvZBZrt167nrruMtC9Klwa2DHu/0xKlcKFo4Q/ZONM=,tag:mFxrNp+NOGHyydfsVFEQKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
