# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.jsonapiVersion: v1
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
stringData:
  1password-credentials.json:
    verifier:
      salt: ENC[AES256_GCM,data:HvyZlMV0aCUVQKFvsrkZ7lAd5AjWEQ==,iv:OlVcXYTDxnEn20O3QnNsRqyc934ol08TdkhbdEDrHPc=,tag:+l/rpPDrO/0wIYQ57XPPSQ==,type:str]
      localHash: ENC[AES256_GCM,data:zx50Auyb7B6cLCUCvPMIsm/drIGCTUwGq8Hvh2/iT0gcO/BuLHuS4AHDkg==,iv:ItCrNmk3Ll7yNyqwbaUUT9bf7UVghSlqde+dWumcKFQ=,tag:BDnLJwqy89BtaCxcujN5GA==,type:str]
    encCredentials:
      kid: ENC[AES256_GCM,data:FAxMMDrxzhdHdEYD4OLTTdM=,iv:K+vzqaLv6HcwngPtvdT/hS4TUb/ddUKcNHrHWCLJ31U=,tag:v+K+roZJ2Ksq0TQj8f5j/A==,type:str]
      enc: ENC[AES256_GCM,data:g2EMOt2C0w==,iv:7CESEHaxBgMwWV1gFF2VCxJ/l6ecTF2+OMTl6zd9yuI=,tag:GVrYRZxgpfOsF1rP1BPV1Q==,type:str]
      cty: ENC[AES256_GCM,data:Q6QQyFTENu4dzJg=,iv:MCrgrkTpf3OTQ7/FdWcAR0KEtWZkcVmTGJ5UZZabOkg=,tag:cx3YVS6OML5oP/KrZHlKiw==,type:str]
      iv: ENC[AES256_GCM,data:AYsKQt+U5T6aEorv8HFRzg==,iv:hf4vZrM2IDjA2Wu0rOQ1PQaJHG/VatzsXuBzHwaEjNg=,tag:ZMyUQpPXlpst3SB9ZkErIQ==,type:str]
      data: ENC[AES256_GCM,data:ZSDD0oFGxJT7IjxhmTnWRojBN3ex72qKKD6HdOVMD/XlyNtEf7NHsU1rv3hKfqADKsVrtg3K4hCRGqqO5W6zSgtLONUeGLL2X/JvKGFGH0iHuG0J4ZCXmLUuPyjuP77RC7UTxzjiHuF3uyzwYd9orrBSziEWMsa9V9trqzR+SfwvZgEd0PII0KbHmMykT/VHb2CEVJhbmuzYtVWmM4RIQZwHR8uYl9ZxMPdvN+9C8M3WCKciOW2+PyH0AStqwpvkOIa6ovr7mNMg+wYyH8g7BBOKRimtl7qaXOK7KMlq0VyyNcO9El35vb70XG0frMNHvN7XSZ9np/7fKlHsZsHV2XTGB1gSzdCY7gQns+3gwkBq1R2E0Th66UoEQen370oOOm2Y2bHgsKZK18noYStydng9C/AQ6fZ9R9c0XwQk4zCJ58SpLk/yyzUgTEluy/qqKSgvGoBQc4mGq/fxfZ1NsYcVjp4mn2Z7pdlp5VliwHwYCu5eujkFOTSipDM3vIB5gdpuv2ZLRfIZL/Hrqrt7WoIqZiiE0+6twOD0gzEgKXwDngsZxpTcrb/AVSrzL/NeWNCL6GjC3jvKQU66ekKIqWXZljS4E078iD8VVbxkEXBLSkRERZWyF/Cy6KAaztNAFssdvAB8o7jPhXiXiJmY7ht8WhCOIaioR1PqkOrYDulL5jtLwZ0KIw2Mg7802jCpxplB9LZ5HYWDPz3yvvShmXXUN0iCsj6tNQMmAsPr2O8DyXiNytkPG6yfTZNIioK+DGy7Kdl7dU7tA/VnndM8D0D6Dj0J7P+nMV030zYOND98c3jHkROsu+hJnL0n5YM/nvvEqqNvV5npOIZwj6Aezx2V,iv:AiVJu8nUGeZotrTAggnB4/dejru69GUwT/eBqRhzTPg=,tag:ZAoIhSMXW3wbnggORPyIpg==,type:str]
    version: ENC[AES256_GCM,data:MA==,iv:ZQVxQGsJcK+40hnP3RwLlaFBJwjMYLBFkCAY1uy/Fs0=,tag:LOE06gZQBrj3l0rHMducrQ==,type:str]
    deviceUuid: ENC[AES256_GCM,data:ziHEeRdG1QXK4jlbkaA4NWYaGWrxwuykKRI=,iv:B/7x5TdSawjVHhZwDkFnOvUeXmkabdLzVpV2Mfzrdz4=,tag:ftt1f5eiTA//q+pGIOYfPg==,type:str]
    uniqueKey:
      alg: ENC[AES256_GCM,data:Sx8xq8ONqw==,iv:QxZBcu8AgA9NK9qoh304DAhCLUQG3knmZur7aL3yoA8=,tag:OP8lgoueCLqriG8SHGFk6g==,type:str]
      ext: ENC[AES256_GCM,data:BAMi/w==,iv:iXun6sTtlpZj07g8Rp0eeojs3LJ32tV15v83+gb0Irw=,tag:aMMViarPa3e16MC+0XHGwA==,type:bool]
      k: ENC[AES256_GCM,data:S4cKERfQ2sd/SxoQV8OuIx1udsRougnMpwaIv9u5dkOc2CDErU+B13xn5w==,iv:qQsZeiHaW/HKdieQWPca8cNxFeFah1KMxNbQ94p9KnU=,tag:Mq3uLaDwU90dArXRQsueEA==,type:str]
      key_ops:
        - ENC[AES256_GCM,data:/17xORwNkw==,iv:YE+2F8oAgTeCYAOyVibi2G2R5IhPGF6++Knm0sR40oI=,tag:k+1vtklGV0XnDlZUxDvEBw==,type:str]
        - ENC[AES256_GCM,data:0ARlFG96Cg==,iv:XN3qt2dwGJH77Q+4Ou5OVE4yE+p6kUhTny4nbR/Vyso=,tag:IqLldP8ISaOZ4UZwnICc8g==,type:str]
      kty: ENC[AES256_GCM,data:IEU/,iv:pr7nxLE3BcLObMV03+iQkhsoCNxrGtD6Yq0bSdYLI4s=,tag:dM72ZVsa7TBGUY8cYl12iQ==,type:str]
      kid: ENC[AES256_GCM,data:FT/b7NU7pEXlD3fmqKlAbGHpVXJSROHHtwk=,iv:4E2n/gQkJeAkg7yRoj7/pRN1w8BdnVCnupppp/AFh3E=,tag:q3YQzYtic5s0OozQImSAwA==,type:str]
  token: ENC[AES256_GCM,data:wI+97S1u6PZHJIavlSV4ULsQBP4OCqW2bV/3J7XGSzz8rwErx6BhE9JAUsPsYCmK9Md475LCJzXIClDL9pzA3PhB0MS2ZDO/aDJSWBIyJZWhRYhsy7zVEY5k9N0jdl2j7hL8j+PALhYBFqV7Ws9yoEg0k1Dmu6JEma3zrlKSEDnYTMk+PkUuhWvuO44Q5O6cwIdXRezwHjgn7AK3U0K6KZuG6Xnztz4P3pFIuB4EZQ50+H1eZ4LQkIg/VKVphh8ltVS4VOwXv1iuDQLnlrypo7gPqmoDvvteCGPQL5lZ1igRnu6BXFGxWBgMVvg+fKO8TgdIVtK5t1xSAwnT/4KxAWMNPSo6u5YEy+P2Aq4Z0lxP59lzQkR0AW2N8XALqj+/7cQdeADeXtgop2NxGlWHuvJ183W/lxcDjwkUOhCTgwKPMxHD0fTjCz1Cq92VYMQ8KAjnPvYhjcBi27Geca7IIHI5l3/C+8kb1lxAPIZ+1s1Lpnujvg/5HCZB1jZUZ9tb88F8h1/cSN8DdG6M3pgDJyu4QrbG0Kf4wvJeZU/FQAv7nzLLqnCz/+L7fYS3t9uxMEVcfOl0P6FmrHfG+ckfUanlZOM5WKgj5l22TiqnZbE21Vgkt6K7zkvvZmSb46ydpqy0yRt6J0gfE9KbJ/P2mSZ8HnZVH89E9F4vTvwMR+BC1HYs8WZ5Fyy3f5OuKUppcVnZWTg/DF3bNB00ObFqvwNIKEZGbJm+j4807GrWCNp2gNB5TUMquwBL/X5DzK9zuPKVLBsXWJwtPQNbAbiRDnOZelE3lL5RuhQ3uJfvKbabDGOO/QVPJ7HEt4eiTpeGDJ7FPSguDrJhZs7OwRymMmdA,iv:PwTujtEkifNQTEM+Uy5wemBVyfcUlMOEob239FgQhrQ=,tag:7wpdGs2c5VAXkM4LtVjIsQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibmt3RjZ6eGhrQ1JaK2d5
        UGRCekYyViswenB0UU54ZGRkYXA4b3ZhN0dZCkR1MWVpNDdBcFNqOStrMzhSTkRO
        TzFOVGpoK0xESG01WDNJY05UQ0s0QmsKLS0tIHQ3blVKaVNtME5uZHRTV29TeEo5
        cEJlazdKQ09seklEclR6Zy9qRW1tMjQKsv3MipHiIxl7VYo9RdgQo02/v5Jh6Mah
        LGagqNu8x4v/y1TEqdsXz2HXBvLvRX04A8eP/dcnBJ1hKVB0COvVrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T16:12:03Z"
  mac: ENC[AES256_GCM,data:spmynXxnuGMMyv00KceQJXyLXZhlB9oao9BPy0FgKqxWetYKqNXmCGZKxRxn92f77C5gF5wMhNNduteTGb9RkJL8xZCPjwZMtO0cqL5ajZQLHQ9oSLLFN+sHaD4Gm6cI67ad9NI4TPNeY5CtarYiCnYvNK8CpZpE4S2Ynb2GYH8=,iv:qc0wyEltTles0k9+sDAeZ3i3vxBvR9OwI2Yv6AZgUZw=,tag:AI6C4WTcZTdy24/9k7Jcpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
