# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.jsonapiVersion: v1
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-vault-secret
stringData:
  token: ENC[AES256_GCM,data:EornSL743iMNq9Z0BIfNHBpZRJs67Vxizr4U4FwpQ/IwaxIVqTapW86W3oUMjyVhQu3cmHrdRAk5d0FFWKocNjs5aoR551lSV/WpnmShwD9lKLFYev/cDzE8TSeJmxM30KPJ3lUTzTEo07Ucp/Tpb4WRNxGloFIzwhWOo2VYJtVaW2rjbwAw0Rrmo2Wb6GFuURUKW6jsseh2Wg/U7yu19sIBNifBeoPLZepHiGf/XLJaCTr8iS6MMvG7EekeF9nhItJO/Fr0GsZnPIVbvi8BPS9JKU8HDQyw+2/OwG89f3XBMvGssf6nnEd7V0yigYPR9vr37VZhIA+lMXFFoj4ytxKZi3W0eAaRFh5MVHXdfo4Mkl2ibvLzL2+C3eCmL+4EecANpjBhBZi40gCU6P8SVqZYktg87gdK/sye1g+beXwJAkMHaComXI+aLOhfo22s1IWqkGm7RnZIGtwyiH4iIkvL2KdizfdZf5UQAKeTcxsSfO3D9CRgazCtdRQFnQriqzc4gKSznmbjpX87ql3UWRisUq+D2V5FfwOqGizJIjWj3EleSZg/Lx1XzBOH80oJbueTWgq9//GDXTUsT5c+Mi4Hrdj3gryRNJmzrRK5Kjxo+P5YrZ6W3UXAipTIOVmXoJ7spMnECK72Yt/9U+n/4p3ZE01WTlKobe4M9EoGTe8cLZmI8UqpGtAbhpEIfJzaETjJDlMdChrbXF4/sXSASiKBAnWaUa+oixyy4fR2u3KvGxaS94XDN3JaVAxATuYNWEdUwzkxg8IYFT8Du26ICZfpJU8KDRlbRkGuncdAOR0QRjLMePA3hhXIvVSihveCmqFTUmyIalMWiX3C51sQJBqgwg==,iv:cQFjjFlxfR5wDsDYHq1qFRCkXd83RTwAJgRV0VgO9Gg=,tag:bFMRZkBDTdDeHHbN9iHV9g==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN2JTMEhZUW1rbXJWc1ZI
        OHpQMDFid1hPbkJ3cURrazN3WXRScjRzMDF3CktIcS9KcmdETUpBb3UzbDcyQlln
        S2VacVIvVkNUWURQakllT0cyVEMvUU0KLS0tIEV5R2JuYUFyTWplU3I3RUdxNW56
        NXNKckFmbmtvRE1odWUrOC9mMHNpZkkK7ksNOspINrT7eF0R1sEnq6eskHX5K3rE
        fwxEpXVRQ89urWq2npqZ1SByKsKwYkubljge13a73wxnErwqx5QdDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T18:38:26Z"
  mac: ENC[AES256_GCM,data:hgcVRCips6NxuFiXpjc6TtaPbDnYOT0i+B54wdwutUk7G/uthGnFSESYFBnuca6WRl8w1eEJsyY+rES7tLxpilVyGdIj9XhhGJkbGSALjYmgJt+pxr/4fcOZb2FL14F44o3rd+xqc92kbEadb9q47HDo1lsaESevpbHIH6zKFe0=,iv:Naos5r9z0UFvmPlh26AiiNZRSHdKMiC6c8e7SjwpoTw=,tag:yL+ne5Z2NFqU3nbKpYqcZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
