apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:J6PiJFWg447Bod6J8EAFQ580vGs9Uyynb1ODC3E7Yf5MXrA7,iv:XEqZRspD+Iqp4eEm2YjJdx3w3diqy8EXpoB33gpDn8M=,tag:egTp6X94ehYqUN643WRhHA==,type:str]
    credentials.json: ENC[AES256_GCM,data:92cYdpI/xCKvDngLFUNm8qnxte1SZrWr6le1waemxmGAVGGvjjpRLWbIQC31hNS80cAxxWfthYvQ2S6GR4ZJx5WIWsezNO7P3IOhGFkodBtaQPMOXdE7f6uTMDQ3z2qkAAymYC6ZZCQ8F/5UssL5T5HN4FQwX7FdxWsZnRgo6qqu1Dd+T92w+fX2J26LGoZjhiOx2DskBfU83fcbrW1opdt9EcsGXNv3WT8sKAgm6Q==,iv:0XZA38yf1Pk+QcPzNSZ6RJq5cBb6pWhUrp9qiT/88+4=,tag:JHeg2m9Aiffr9CY1KZHxPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWlVHTW0ydlc4clpzVXRu
            L3NJdU5DYlAwRFdndjE0YjJCcFJJcTIyMURZCkNIMmlSNDBTdVkwYThIWXRhVm9Z
            cnVQS1Bkc3hwWVh6WEU2clExZmMzWnMKLS0tIDVSZE9qUjJhaE1pbkZCM2I0Mzhl
            WjlVK0RnMng3K2xleGRLbXJ1eVBVcDAK1Ug01xw3HE3/i0lHUutiMYghJvmPHZ3E
            T9pRC18y8qDmlZ/dzQSg3n07+OV0+VmtjIsZ1BifseG+bPPyskXaBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T18:44:57Z"
    mac: ENC[AES256_GCM,data:DEo8Q5wyUG3IPQZhInOK94MWgBoeA9McwH+VA5dAWeiI6M9RDxl0Nw/8roZt1nwKTtzQaRD8TeVlWskf+7rRkxOiQ6tAd2EcturkdGL0pdzSsro+a0OkIZxR7DL2URL+FoeV15zDa+e/hqSFj0VCt7ZJZx5Blh8bb3l8+uxdW/4=,iv:6/d42jhnp5lTeGMQM2NqC7ztyFFMvC5dWA0U0y54pUY=,tag:JEOE9hB3WexW/xBHkE+ybA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
