apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:cILiaOP62I2rO80x5kzdwqemy202BhqCVxR6IvmkK9BtJn0q,iv:o8PnRgQx3eY3BOeSqOs0F0WYOE5dYOFsVaK2/ll/tgY=,tag:iEIAxANV7dOHTbw9BcIRHA==,type:str]
    credentials.json: ENC[AES256_GCM,data:dYbyftHAFfUV/KczzztnIgugqYGTArVoyt8Ux43+C+Gy5SXLeCw3PJk9fQozbxNNEpzt5nag8PDRj/t2ztqLZ4ZYOkvNtv0N23I8s0ZPfPfWc8fA88Weym7Q3Y09lUE55i/M3cclhz5LVffJTOVgkEYma0BQMylup7d3Fvsc234iciOgw8fSAdqe4FZ12ySUrHGFzuIpSiVX7F0TGlBIfZHM4cc5RqIUEGKYubiglQ==,iv:Pi76kuavx+zn2o69/Tij6PzKrdzuPqXg2HQr/i/K51w=,tag:MNx/hkQ9/GwE/m32pibTvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNnVmTGtIQ0pWSkFxaHZs
            THMwcHkvTFZOK0tUZ0NWQ0V3K2ZsRFhTdmpjCjFCeUNGbERFdzJRQnlPNFdJRGZY
            QU1jUkdHN041elpyUkYvTWFBdkhHeW8KLS0tIFdoSVBzWElvdkYrUzJCMzdlZ3Np
            blFCa3Z6b2R1d201MWtSS0FkcXozQlkKNcE0a8qtIAsm5kPc5Or30j6nTleOOh9C
            t8glbLCE0h9aUnA2NRZ1craZ7G9VExyxo5EX6/LHd64ZwoZ4JFfN1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T19:32:32Z"
    mac: ENC[AES256_GCM,data:nJGvMgzqsEyO419Rro/F/DjLx41r4T3ZCc1hs4wwsszOuIoi/aAuKFuRTImmG/0iMclk9vwaAwDh0pX3n8xl92V1OC/+NiRqKHlZUeYknTrLGnCOzFxu1vv61mfYj55tSBRFvtiTDnqgPNth2lSTdaLwxevg4e3fJ/6OvNeQHRw=,iv:F+5htwgm+LsDj6csWjaGBgXUwLKUr+m1D3AtManLhso=,tag:y3DnVLtp8ALzHESalN6z2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
