apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:amyD2QqbFs0QK7i8MEkauouo2bezgO+w/2v7zXYUKYL8Asm0NgsHLw==,iv:nhG8BjiaMrkp36+QqIpWhtI9UWnHMzNZZpDwtDDPIbY=,tag:JPuJ549tuImWJ9FBDqeb/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNUlZVTFJNVJ2WDVIYlJ5
            RmE3aDNNYXBMTG1vK1hzNHpwaGRVbXJKNDBNCmZiY1d2VlBBL0ZXUG42dHRCQ0Fz
            ZGZHNENaMmg2enExREI4RzJRRm1XNTAKLS0tIFg2emRodHBsbkJTTlZMM2dieW9m
            VmRtWW90UTUvdUZIMGxzNEpQNWx6dFUKhYGmJy7s8+6FNUZrCnlDDq+/UZy+QtxM
            FaxtCyIZ1YZutbRu/vLjmUGDFmTnJMy87rOv2UkxlhMmiQgFmOX4Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-25T11:32:48Z"
    mac: ENC[AES256_GCM,data:D8GWbs7GlelY0jn+dU96VR1I/lCZ+27wy86c31PiFh/WyrOCQhdl49O8G2YMDhWV/Ykqf6N9Z4tNOqKnk3WIt4//mcbwJQZ9j3WEkBvLEmDVNwPHI5DC0pRM3hHkU8BZEuV2MpiTYiRsj+kMv963agTmKI1TjX+SNYYkjJs6fRU=,iv:9dj7mwqwUwQVePwH47nuX9mAQb76+Iahom1RFJNvgWM=,tag:BEuNF2B4HHKW9cXgXt+wJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
