apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mayastor-metrics
  namespace: openebs-system
  labels:
    app: openebs
    release: openebs
spec:
  selector:
    matchLabels:
      app: openebs
  endpoints:
  - port: metrics
    path: /metrics
