apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    api-token: ENC[AES256_GCM,data:giYfTfrSBJN7KiaLYef1nyIX7XngOm5Z+nIMkRI9aoPUlthej9122Q==,iv:8W1TOMCgFIxpZX84iwqk2QcHSckWsF8+vs2WmhI9Y/M=,tag:QQPmop2feVUsN1HWMBVMrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbnQ5bmJMQ2ZyVVR1c3ZQ
            VzRvWlRrNUQ3R3I5UmlzK00vbHd2RTJiOWg0CjBFUmZObXpnTllON0UzOUdnOEl0
            RzkvWEYyZ016eE5pMnNIbVlBamJJUXcKLS0tIExJM25jWFVFdWl1cU81Z0IwbFR5
            Z1Qvc0E4bmFFaUIzZTJCNk9LVk5OQnMKdfA/GSxY1r8Mt5Sh7IFEo6rYJt3o2VOw
            yHzlrOHlU85BTud9INyE0akvOnBpzwwnf3jcqf3YLOm9t52J1KwLDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T21:01:59Z"
    mac: ENC[AES256_GCM,data:h4U9R9TxWcq2p5tL0OzKtM5yIeHxo7Zl9IXaRNwgYpurVZIc1J9GhM/dCQI8PZnU7RkPYBRVap3Vr25A06LLCYeWYtKSk/Vr0LnBWU2RZQai3gbiHI421FOi7VL0j9RZNqNbfBRosnHqlbWLFUMiZ40+UDYmw5yj1sMMmL4yd/4=,iv:Ep/AR+HpR577G80Vu8msAR+DdxpBFqBsLAT+TsgZ6Ww=,tag:y9wImxp+vGms8/2TSQgczw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
