apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:oT5p60TIFNFqjhvQIYkAmhCN1fk+Frz6upriF46IwmBzONr9nRKG2A==,iv:gm1lahnDK+cEzijAjO64BOaV38fpRjVWgAuiCBwwclk=,tag:X+zQPNYNFiUONuEDhADKqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNDNBdjRLRzRLbnhFTElk
            ZEkzY0RpVWU5Z3ovZ2tLdGNKQUFWc0VmWlEwClA2MXFCRzFjSnNHVEtNV0QyZTFq
            Vi9IZ2NjdDAzSDBHc04zMFN0dDN5TjgKLS0tIHZ0TjIrOWRyVTJLRkRzUFFpbUQw
            eDJrVmI2dExlQTV5U2QrWkdYOSt2UW8K9Y4xZQjLNrZBhMrmberqkZCrlaOtvigt
            s5L/mEtmmFqSATDGhNFqgLRJtzm315cF8SHhDAbdXM45n1M89V8vhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T19:57:08Z"
    mac: ENC[AES256_GCM,data:XlyNJ/4eA7VwepBCDbayIpCalt0I/1zHJvfHNc4ALKZ96c7HpZRzeN00VI1gwsIqlx5sAzFKglUpGVKZ/D0Ofm8+ghdcyl7h54gUK7kGA8YBvm8rMyBoP43ldwzkms1IfwaUSNvHAppzXwdPDYQ2091oZSOoT8HI0QjsA4+H1dM=,iv:g/aT3DTYFma9zDYnjKXVefTuA8O5/bD+B8vvK+g9UKU=,tag:7tOx7GgAigAWRBBYHRhGDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
