apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    api-token: ENC[AES256_GCM,data:B6jMXc0flsAFQauPdCtawKv+ZZlpWQOcQbspI6uUb21UBBq8obWhxA==,iv:Vzwwujmym8aDP/03wLEnAZ2PSwarrPIo08UKal2W/68=,tag:N0tdR0Qt4q/jKtBHRzFqVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYlk4OWxmSzVqSHJTZWcv
            T2hSNzBvVW80Nk1BQ1hpRm1ocDJMZzF2U1VvCk0xYzdma2trK0FiVmJiT08ySFFq
            QmhyWE5GQ1VwZVBmQnh3MnhncGNreTgKLS0tIHJLTzI3bHpkSWpyNDN4bmZING9v
            N08vNW54TnBISFRJa3lCUjM4Zm5HdmMK3PtV22I439+2OJwuCkzpIGP0oWGj77AQ
            1JEqqWlcHK7fvQZRnzykUik/tWIgdPHlnghSd847hNt7CAsVZPXRuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T20:20:17Z"
    mac: ENC[AES256_GCM,data:FaxZKjGwxTMthEKlhM/oQrg/bXzAghpA8jqkNAXViEk7PHkOemVZooO95auaNb+EnIZS4XIB0n7HLdD6UPWmQZ3IHPSvE/s06OEPoV+SdNN5LuHWfdc7SKOdXdBRGXwL4OklmZCB4vD7PpHhYmsj9oD7DEPpiPa+VTfIbh2dcbg=,iv:WQ/V8sGvXgok28dcK/jpyuelZJv3JzrcudaxmdrTrVs=,tag:A5zA8gdV+XEqIuAFObXx4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
