apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AptQ0QGCWWk=,iv:EGrRGB9CtCLyWaTo8n0sgNvNqD7tpCmitCHDgOdezdA=,tag:hSJHddW5fVpOov+2n8yArg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Y/dRWMnjWo8050iQsxhVgcRm,iv:FIzNaP63pAOqBhJMCyBOjlymsz49dVRO0MsWfj3qAXY=,tag:8CQYbtAwrbDoTtaAtMfVLg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/sotjZHFS2iGoEa8HLys3DoQEVlBlkzR/RojVp5ILMHBqwAY,iv:SbWKgBw2HPb5vNqbXZMkpdjPi3dFtdOyF+eHvY0CucU=,tag:IL6eIEwTrDywj9fN++B1rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbWhCUW9COUN3NFRWQ3JH
            NHk1anN0Nm43aFBNUjR5VzZGVzJKRGcyNkFzClJRTDJhUGN0c0FOUU9DVTFiRmdQ
            ZDlSeWp5Y2dvZC82RHF2Qm9vMFZxV2MKLS0tIDFtdGJCaFFpWFhYVUhaMmZzdXNQ
            dmJpeDErWFkvT3NlQlNUZjBIaTFoajAK+sJEUJsuFIVJk23IuVBlt3UQBY3rgmn+
            AZoorUbzr9PO151jQHTa9C3AKTS2JDFvUONIV+ywgZK12NHHxKwcYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-20T11:33:39Z"
    mac: ENC[AES256_GCM,data:XCCj1iMBdoKQpF0dfFAPKObRl6qz7Zm+MmdwAX67Dyg/+RHPRJmql+YgmQfD4RiVx7qKSVNqi+lJSVhbfdaK+CXmwxvtyt+uOdi1vb2NjM5hblvgxAb8cpl3LMf6mk7jCC7PfgfKNeXYojk/0SqG2rdUX94xAqeAuriSv2trAaA=,iv:RLiDqssDQxaNoCxyaJmwLGgC/FTp2ElCJsmk1j/8xbk=,tag:rhHh5G3gmwqBIRa2xP32pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
