apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:uOrEnbcor1/3bOpSWyTWSFXGfE3yKryEBmWhtGxI+TAEbaSscSoTESBjdosOoeTaVknkWJ5VmxILU8c+yUuFIyp7V2SMAkq9vDY3Iqb0Z5arjMzd/yRfV/U7/6MvEQ==,iv:DxF7g+usZKZQG6ptGCGBMa9+EwWIVAscCisrwrOHcFw=,tag:Dn/r5Fd8PStd64cGU4ho9w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:KtKhewmyUYs=,iv:w9e9V0H7Mop2ZuB4CnKZi3bXshEc3D3lpyeo8DWUSt8=,tag:ptrbA2Zc4QLBa8iYCUkxeA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZLjNFxpRDpcuoettdrP/IcwQ,iv:FKUPohBfDY6DrFbXgX3n/FuvnSDR7fab1bHwcP0ggdA=,tag:gfLmBNMo1ZCmfeSqzp+02Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:DVZzTQc0Ft+hpZ+HtGDtgORvweVGUv32Rgy+Bc4ON6Nct24x,iv:2M63ym/vjfg/jLup5nHl4cjA20NwScq0dEHO8WSoIPo=,tag:juVGDA/tRFbPh0b0Numwxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNTB3SVUwTUZnZ0FmRk1y
            M2w4MHlNVU1nQXUydjdHdVlYZ1lUQTlTRGkwCkhqb001Mno2cFdjWmNxTXJUSTBv
            SnZvOGRtRjVybXhDUUhac0FTeW9kVmMKLS0tIDlNVGwvWmJsTEV5MElNWVdmUWJF
            Wmdnc3BrUmJwMG9SUE5Cdi9QUzNmeEUKEBtnOO366/9SI+2HWh4MNkX8KzFK1ca9
            fcAZI0wlwg8fH6grSplkeqSPZ4QSYDjietj2C2AzgyIYfY0cMIKQmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T08:39:21Z"
    mac: ENC[AES256_GCM,data:BLXsUD0aDi5HRAY0zXoMRI4EaMqHh1qrriOuENdwLs5rd3XwkPHQTzdJMbmikrNmVNp8p7S8sK4dhojaxNbauzq6MsfUl0TnXYvyt3JpIs0BUphsZ0WfyCGBXRLzERl50TVDFgy6S1W/4obxcQimtYzeWR8ugKZ7qRVjU4JEu70=,iv:9uBxQm6zic+fyQeTMpDEWteZlptGIxKbE3m+GgWiPxo=,tag:PGS4+35ne4qv+seZTwtWMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
