apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:YSDQ8HfP/Bu3ydvn,iv:5dCnz7vEHaB8NqNmg1SrkrrAfRxs/7jZ1IZzMSd5jR4=,tag:nLUoPS9Z8sJnXghXgLw0fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs4yny0mulfz0rsaswzx4xwtk9k455j37wtytsg5c3796t082yfqvpgu9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R3ZZWTNCdytWVnVmMTZN
            TWF3dXdxLy8xZEkySHQ4Y2FzbW16OG9BVVFjCmtUY1I5Skw2Vys2Y2ZtMDVKYU9O
            cnptVEgySjhsT0JuS3dibTJaQlFkc3cKLS0tIHIybXpCcUtMOTVQQnphaVlpWmpk
            TE9VZGRJVjRnVFpmbzU1MTVwdkF6Wk0Ke7yFDO4tZm8Gennti24JPG5+DgjT6IP4
            N2wyQyCoIFXZuaWQ5bCXpmpHUn4ZZKAJ0K9Ra76LobwJXvJxVqDK4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T17:37:33Z"
    mac: ENC[AES256_GCM,data:gYJkcyCMJKTOD+fE93eHne8eRsWM4CS0Owe4QgoS2VSwAHt10eXnQY4KYQ/e/+IFcolpgsRBmZ8j4gJl1lRXjIsWnK8ZmbMTbmYIIxkavOiLabQoUrGZg3CFtY/1+29liI8JudLgdJHEGzKL/vYOMBa9qpu61jOM4C/eOwAllNE=,iv:SGZsEx3Gc8fnu7UUyCe1LMVapcqzY2LRzhf1ByaZx4Q=,tag:OC+RLwGMiFfLAH+FjsHeIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
