apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:aGkPe3Cwk8M=,iv:JIAbRT8fhBYlRVtq7tMLtGXiKs47QFgb48DXAdXTGaw=,tag:qO0kov37HGZwv/BPTrEJ8Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:HL4m+iZlcgB4EoWe2lSc7YlB,iv:Bl3xPX9A2y7KpxCMZ1xB0ikpPX1vy0a61QT1ovqaoag=,tag:jm6Q1/Ll8+rw+TqoI+8c7Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4+CTsKqpOP6oOXXjGABCeaNHPyFbc1gKrDKKZXOTm828lSzb,iv:/9VrMSF1M0CIdiIXVVIyreYsLygNVJRmddm23OcsFmw=,tag:+jE1MgrTVnKwdcGYdvI0MQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTW1SSXZ6UVpNSCt1TDEv
            ZFpPUnhGdjBObUk0NTVKR1VUcVIzeW1raEdjCkVKRWp1bktPaUI1WndOS3pGNUpw
            Q2FsUzg3TlJyU3VWTDRpV2cvY2JZRUkKLS0tIEM4N1Z3cFNtL2swYWlrSTZpNmVF
            TjJYMHNpRjFrM0hwT1R2MFRWT2o5MW8KhpM9JM6AGUtBtVPrUmUTVMQ1h04GnfAQ
            kO5cg8rFR5He4o9Z2G+9XY4OCfPwvqFsAwBIiFPi8a0BeQdx9p3i/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T16:51:18Z"
    mac: ENC[AES256_GCM,data:wknmZn3czt+DbzhVdTFT/ssWKA9AGG3KByYmv32HWDi6oIvVfWuo3qmMtW0brFQq61ui+7eAMECP2r2xWQ/lstmUG2MX9E0qSVWbkBQYAKBIoYb/Km3OBX2fo5jaH0XhPtG0syv4KjU8b+nOlDW93quwLnKsCU7RGNsycuf7oak=,iv:O/LuklnN9pl9NNZrZaTboqZfptrvUUmW9tWg/ELS1nE=,tag:7UEtvbyaMiS2zA55TBkfHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
