---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kanidm
spec:
  chartRef:
    kind: OCIRepository
    name: kanidm
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

    controllers:
      *app :
        type: statefulset

        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
            fsGroup: 999
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: docker.io/kanidm/server
              tag: 1.10.2@sha256:5d671b5ecb47bc0b5f37d3306f9e7b9b387998bdf5aa451d76a4e764cc05f0fb
            env:
              KANIDM_ADMIN_BIND_PATH: "/var/run/kanidmd.sock"
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: &port 8443
                    scheme: HTTPS
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
            resources:
              limits:
                cpu: 50M
                memory: 100Mi
              requests:
                cpu: 10m
                memory: 50Mi
            securityContext:
              capabilities:
                drop:
                  - ALL

      provision:
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
            fsGroup: 999
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/m00nwtchr/kanidm-provision
              tag: main@sha256:bc6b74f818661d369c98b9f3414bf31421450e888455405a4a7a112b5d6f2614
            env:
              KANIDM_INSTANCE: "https://idm.${SECRET_DOMAIN}"
              KANIDM_NAMESPACE: security
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: *app
        ports:
          https:
            port: 443
            targetPort: *port
          ldaps:
            port: 636
            targetPort: 3636

    route:
      app:
        #        kind: TLSRoute
        hostnames: ["idm.${SECRET_DOMAIN}"]
        parentRefs:
          # - name: envoy-external
          #   namespace: network
          #   sectionName: https
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 443

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          *app :
            app:
              - path: /data

      config:
        type: configMap
        name: kanidm-configmap
        advancedMounts:
          *app :
            app:
              - path: /data/server.toml
                subPath: server.toml
      certs:
        type: secret
        name: kanidm-tls
        defaultMode: 0400
        advancedMounts:
          *app :
            app:
              - path: /certs

      empty:
        type: emptyDir
        globalMounts:
          - path: /var/run

      icon-cache:
        suffix: "icon-cache"
        size: 1Gi
        accessMode: ReadWriteOnce
        advancedMounts:
          provision:
            app:
              - path: /data/icons

    rbac:
      roles:
        kanidm-write-secret:
          type: ClusterRole
          rules:
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["create", "patch"]
        kanidm-read-cm:
          type: Role
          rules:
            - apiGroups: [""]
              resources: ["configmaps"]
              verbs: ["get", "list", "watch"]
      bindings:
        kanidm-write-secret:
          type: ClusterRoleBinding
          roleRef:
            identifier: kanidm-write-secret
          subjects:
            - identifier: *app
        kanidm-read-cm:
          type: RoleBinding
          roleRef:
            identifier: kanidm-read-cm
          subjects:
            - identifier: *app

    serviceAccount:
      *app : {}
