apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    EXTERNAL_DNS_UNIFI_HOST: ENC[AES256_GCM,data:VEfocjsJ62irSBGOpv38oA==,iv:4mb+w5xQTH9KD2BT8shDc4d7iXb9SWXfqA1xw+6WHOg=,tag:QglgTrqkQ/VkPnJ9GnIDzg==,type:str]
    EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:aOulblUjfvLdHF6mz8u5vcfGO4mp7c7UyRMBE7M1hak=,iv:MTUjEwutD5ggYncrY6ZuS/zSsStn6NayNFA7+i9Foi0=,tag:HZMagU0kCCfsobMDm0sgXw==,type:str]
    EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:yzysFwQYCrhe/AC/0/2qSRIE3PS11xbiwh7cE4nhVmVZ/LKT2LlnhFSVYBQ=,iv:2/rU8ovf3+p37A2KgmBiAuOjAbtYGlIv///alYEuDPc=,tag:sswdoAc9odU6WNa90D6xOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ3E4bmZDbW5PUEMrNjFp
            elZDN1pyTjVRMG12WSsySkVZMWQ5NWRjZUNzClZUS2cxZWJFNFZzcllLSHYrNHZL
            OTVlOFIyM2V2K084d05UdEhtMUdLdm8KLS0tIFR5dk9HUmJranlENmdrZjZvTDZV
            OG50RTY5ZTVJY2FDY0R2WFRXdVB0OWMKF+MDAIxUVB3q8yKOISlY5cArvTFgh5RW
            Gcmlq6qhi0bcyGijpWpLENjMFx8rfF1Ksv17zp9CjNSsU9Rio1+myg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-20T16:31:45Z"
    mac: ENC[AES256_GCM,data:VZswGpF7KMsuiEezZ/2Ogf00TwerRTEu01cctVROoRx7qEF483sOR2F9AEjBohc4xh/TVKtNYZxHNzrAP5uzxtQNwqk5F4RaKphVW++aOf+TdrSeXrGgAkncs7KALitMT5mLqyO0yGoU77aN1G1L0qlAxpG4iE5Lu/GK+7dYdoQ=,iv:j/TPnW/dZqWldeBC5cCWbvBgbwPXMCZoCvVfCd7AGqE=,tag:1C+A5zkuxzY2J8aeYfTpBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
