apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    EXTERNAL_DNS_UNIFI_HOST: ENC[AES256_GCM,data:bErcJ//VsyhX6aLjKo+6yQ==,iv:D8Fvu3aUIK2ky8QOLhDHWpH5DKMJuIahKdYlOxdrtBA=,tag:5Y562tWIgKss8fc0Hc5q1A==,type:str]
    EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:8NlQ0P9N9bUjUKPrO1Vc2YBlDgqFu04=,iv:eomMnz9nD3METyzD63sgqxTVQ0QShlylgCVUktZ1n4g=,tag:Prrtmw9G0FiNvOrRHmXaDQ==,type:str]
    EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:eH0SYBFDn6EuTOjk4/WdYanCfr8=,iv:HLOnZwgoCHm2Z8tXj9G8vSGjMomDjMbqPtWyXvHGLiM=,tag:1R9vCRnX5TOxoZ7ik+wYKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN0M2bzdOajZ1amFVOHlU
            UTl2UUw2N3hDT1VvKzZuMkhVQS92ZkRBUWhJCkgzcy91RVhWU3cvY1ZrWTk0L2dr
            SVQySkRiSlZ1VXFaS1RVT1RRbElGekUKLS0tIHJCSTlLektEZHplK3FVS0lPS2Uv
            Z2pPUVdWQ2xrQS96ZDlSVGIvRE9TLzAKRfqkWKIV2RmzP2alFr7yGFZH7858Y/3W
            P5vEIflhe8VMQSfDugp4Z6py8Zj/3cqKv2Upaig9xzyp8QcRrKIynQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-23T08:08:18Z"
    mac: ENC[AES256_GCM,data:WjnQcMPrfDx7BK4/HcGZ9WaOBEzbNrrgfXI69HhPTW7Q4IBm2l2e51rsH9oSFnRkeqIhw48IYGr7KWByTxWfD7LW7vjvCjiQ/eif7hWuOMNCMxzn0ZJOAAJngjIkN2ImXN5ufcfvf2xxw522LaKIYO0kT0/qnW8i/tNSQQ9UPeg=,iv:UaTqR7e4Azr+bPoxCyuf3KsSQpi5KuYeLuKmuf3DCHI=,tag:34yOp3Lt97B3OOZrnYZtmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
