apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    EXTERNAL_DNS_UNIFI_HOST: ENC[AES256_GCM,data:kLqXcQYFIE9mDUidCUjHDQ==,iv:GxD0lC8b0GnJoJQYyZ3eiq6tW+G+Mphj2tiT8muWItw=,tag:72KfGYEyPsKWETxvitywRA==,type:str]
    EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:nkmNPhFXPdrUWwxzjLBCOrqr1D00VsY=,iv:ke/E1GxQT4PXgOePSgkBW/C9gGTl71o2c6aB43wTMLg=,tag:Fv9hLszX99stC6boyZonDg==,type:str]
    EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:el61APb+IdBhgOZmKZM1aMLvvX8=,iv:FJMm+1PuouL3eCbrDaTH5VKIH3pYTUxbfsDwpU9qsCU=,tag:2onUg82bfPzo8ygq8bD6bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSFpXdHpqdExCZDZxT3M3
            bis3WHA1bWh1ajVYOG8reVkyNkVlVG1BQ3pnCk94NE9tdFpIbCsxQ0RRUDZ3Rkg4
            WjlRTG5jeWZ5NHVHSzhCeTJwZkJlaUUKLS0tIGVvYW1NOGl3bEtRbXJvdDVlcHp0
            dkprNnpyYVZBNlRKUEs3allSOGdzNVEKHtaIT1Sprjj5PZUE3zsl7Nm/UU5FhLec
            aKu6om+XJZ2labdVAxirdXur9wOLR0jyBSZgAdid8aAT1TOaoWRe5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T15:31:41Z"
    mac: ENC[AES256_GCM,data:UwkcAE3pajAKcBP+vY/u0+sHxASysAZFBte6AWzvqfeT0laBhKXSDrXogHFDyS4e2qqpH5tGQ2eGaRmxv9AG1vfLU1QYBD96QB3+ZraQhm7BxQdl0jj4b6nFikVtopi7jv+z9/8gTbwZMNaaug+Wl7r2hGc3GF0t0UO4tiDkAr4=,iv:6EUvNFi3TzWjF1dwHOZ5fJViGDHVo3ZREyH3aTbWM0M=,tag:83FqptcJeYWEfHfROB9ZGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
