# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bedrockconnect
spec:
  chartRef:
    kind: OCIRepository
    name: bedrockconnect
  interval: 1h
  values:
    controllers:
      bedrockconnect:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/pugmatt/bedrock-connect
              tag: 1.65@sha256:878d420e23578c4e44f124cb2f9ca246d2c844737b9286ca085d15ad33e789c0
            env:
              TZ: Europe/London
              BC_CUSTOM_SERVERS: /app/custom_servers.json
              BC_DEBUG: "true"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      automountServiceAccountToken: false
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "10.1.1.48"
        ports:
          bedrock:
            port: 19132
            protocol: UDP
    persistence:
      app:
        type: configMap
        name: bedrockconnect-configmap
        advancedMounts:
          bedrockconnect:
            app:
              - path: /app/custom_servers.json
                subPath: custom_servers.json
                readOnly: true
