apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:0PQDVeteedA9xh3rIap4fGB7f4DmMhI=,iv:7kVGIFSeK78OL/8ENaffjiYX531msLfJjAltByKnMXc=,tag:aM77W/9tMkeNJeYZInd2Lg==,type:str]
    EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:UgyWInJD1TvqQ4MHzogvZc1ZRq8=,iv:W/+1B741qRVSwnngGBdzsRUjdNLSjpsVU9nWvHg33A4=,tag:2JcmDt6hIqiBwGUSi8M9bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNWVPYlRQSG5ZT0ZTRVhr
            d2FiR2tzQ2hIUXN3QVFKa25OK2JPWWVvVTIwCm5iWm1vcVNPZGszVHVyb1VPSkd0
            c1NOUHp3MGpBR0JZUVRUMzFjbGxTYjAKLS0tIFhEYS9uTHNSK2xybVlYYVZudVJH
            Q0xiUmNJNmROTEQ5eFhrQnc4NjZhQ0UKmnHLs8BziCmbl0iLA0pCED1I1tfd52/t
            jo3j0bETC85S4AQIgj52svWPOxd7ajk0ebn8BjqCXXXKHDCCA3AAaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-25T12:33:53Z"
    mac: ENC[AES256_GCM,data:PZhHY7shApzZrtxkNzN7ZyOD/44ei4KIYnGoNHhLESr+AmqAvHvDds0Uuah4VWd69BpbHpGSSku4HN8C9Gz+JDvQZRDXB4a5eprrbtD8up2SVvTwBlOEeiwVpBpIfias388wRqj+4YLTohs6RXZ7ExL1xovje0dP1yPu41nZ+Zg=,iv:H5gdJzalU1VVN2J8B9O13GKd4atqzitdzg6Vr2LjbE0=,tag:2dEFw9wajfdvfIIQJjQM6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
