apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:MHJDbENVe/QlUEHxmFHFbMIwaXfcimu8RlZAojTzgsi/Z9uD,iv:A7ijSvr8nxrPmgMXGewZMw/UC/yYnyHBwgzoiN1gvXw=,tag:TruamzN9V/k//O8fG2SzLg==,type:str]
    credentials.json: ENC[AES256_GCM,data:WrOw9diLOoGdKHUyvC7bymCxv64Gf2LDcCA3ArK3nIuCbB++UE6bM5oL/VkKoB1HzQwjKznfZg5LX0xLDUtm35odU765K7cb8d4K0pvGXaLdFtiZrQH6kEhRNELqiWDDQOQigEriBH4ioA40ql8X5V+R3QBykcQaK5fPVZHRTr0PQeRHkE2a9vLbieuyN//gyu+8XiulDu0loDWEs5bvQ7RGUzCAkfcjPebEwO3KjQ==,iv:4/LULme/jsq+MJbeMZuVFWCwWmkeOchH/cKW8YILlVk=,tag:B9vWtduJDp7PiUvjiqJV1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUnJXaWRRV3Q0VFpkM1l2
            OUU0VmhNQS9zNVlnR2tXMFZWSVNCT3BmREhJCjYzcUxQZUFHM1dNeDJKWUZYdGlh
            QThoUnR0Zk92MVlrMG1WSWJ2WmI4cWMKLS0tIDQ4czUxMkt1WW9IeUNaWXhMS293
            N2lQMng3SGlZYThzSU9EQnJNUVZEb0EKFeW0myPZ36mIPQWsz87Cd+Pp328Ohmzq
            GlI/WsepLuIhWw0z4ZW7xIZD51RHGX2dqXM+7amEDxlaB8if5WMmdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T19:42:08Z"
    mac: ENC[AES256_GCM,data:ERombw0RRIKtmjHjNh5pbyQgAz5hiNApJYNBo5EiRkpI+XR5KxXICY/vnfOHVvIXVuxzeWuHxpNhPjMST55APSnyuUqn5I4jr3CKoqZGYhy6PWhsNPQWAZURewegqjTGe5nxL/J7IebYJGRaml8XM/r5FbWvDR7Q2ldzv1NomHU=,iv:OYr9PPYLIe4Dp/f77TjOWyiRW4Ud2gZ5zVZ8mP1tpcI=,tag:wTntNwe8EcW+uaGC81R+4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
