---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
components:
  - ../../components/sops
  - ../../components/alerts
  - ../../components/kopiur/secret
resources:
  - ./namespace.yaml
  - ./tuwunel/ks.yaml
  - ./element/ks.yaml
  #- ./mautrix-discord/ks.yaml
  #- ./mautrix-whatsapp/ks.yaml
