apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hIcN+9vDtkQc41/faX//vutdpshWfAgUB8UFbpLEvpIlvM8E,iv:2K/7LWx4ZWmSHJTIdl8wKtMxknqC0A2VHZI3p5lyBhQ=,tag:0oxt/ZGfT7xfKe6EOqeIug==,type:str]
    credentials.json: ENC[AES256_GCM,data:qNpecyIIlbrOxKXc+bAoGd825pde1bDf5FsX9XwyOG10zLuXunpil52945TYmKGeSonLfAtVHcoipQEtaQXVJfXqBDdVd219JnCFJRTzOsrIXTrubLweO/ey6lXzdPiiHr/CcH1RD/u8EFEib7i+932XU0m04M+qVAh0C9yJgn9QIslVUsJt3GtSgRV0IkQfABWhmR85BTZ15cXstP0qgZPYQLInveaD7T8sTB2yXw==,iv:4lvgmkfVkMQhgkLgyQwQTszqADIUl7rl6huFykicuG4=,tag:JfqQUCorfXcsQQEE5WIU/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs4yny0mulfz0rsaswzx4xwtk9k455j37wtytsg5c3796t082yfqvpgu9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZUpYNk4yRnh3TkFtOGZy
            b2Z0WFk4UkUwcmdiRFZJcDFzSWVYNHVvaGtnCkEzY0JXU2R3bVNMVnJCNXY0N3E1
            UmYrNDJyUlNjb1RJVFlwWkhiV2NHK2cKLS0tIDRXaWt3SVUySGRvUlpaWE1BaXhj
            b21iUitra0ZtTm0rYkExSWl1ODd1dDgKyxsU0nN0b1NBmPhaP5bwy9rmun+fTKj0
            hT876f0Hsn5QU0+JZlWBaLAu8mZk9jf3YZfWHCMnlkWqLRQbhFL/lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T17:37:32Z"
    mac: ENC[AES256_GCM,data:OO2/sUXklWhYfw33+ysKEBbQzM1T57LOZoWO2/gcoVViwsefa8fmwZ17jEJKObtdR8trkFH3NiHBERRhNe6OaGyL6vTX8weuwE5v4wpK2dzgi6Jhf8k/aMqnmheZMshXZOz5HHRuo8xLpPRpmxniHAWYIm1fWmluz9kl9dv2pGI=,iv:TAhpyTFVQCEYOlybAM13eJBzE+WqLtxCBqx2N1MWSPg=,tag:IrzMa1xd6cW7YdCCVQsQqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
