apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:5y+DCU3DIModWz3Xb/NyPb9FgVwlopVqvcDXqEHrJqI=,iv:Q3ZpvcB5LgBj7XYKQltJXIMboAc6UVBX9KjRSjR/mUg=,tag:lSIXLXFc6f9UC3fha0nB1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUzQrR3NBaDIxQm5lK3Qv
            ZFJkVTR3S0QyRk9GT3FwZlVzTGNjV093QTJVCjhNLzhQRkxRTGpMMVZLU2M0akE5
            VW1ncXdwNU83bjNLRHlTSjg1eTVzd00KLS0tIFltUjhmSldpQ0xOdEhkQzRFbG9C
            MmQ4S1Z2cFZvbUVzVkR5Q0RCM21BbTQKVQP0axNp40zRXTbit0yfFn295khpWULE
            kSiNwlgsbExZLJdlG2n/KCB2m92CddoZV9eb5ZSKOPwyCeT3vWr6Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T21:08:58Z"
    mac: ENC[AES256_GCM,data:1mhehS474CEWlusn4LnUhgtMpaIv0I+GKGu4pNn4xEf3FoFRGdoY5b7JWr9D1rQgLcQSZ4/fOaR3Bo7Oj4xUrOPCRhdZzvwECAaPanKzvw4s3g6j9NjDggrx9ijOIhu8+XIOYR/OA+iaVmsZx+XfCIWi8MpS5rxj3xtoGaF9cLA=,iv:GA5szKkK+6HW072BUZa5gYs7cvR1KgFZv3BlTCtGAQs=,tag:IYZ38DG2qW72cBlS4HQ6Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
