apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:KZPajUBL6cRxxZYCrcPMoR3P32kOPNZU0Uq9XW16QnA=,iv:tJbg8Gwy6Dv34XMYjNF1Y8mbMcoJ3VvT47L7C0ogLYQ=,tag:LDmuDvys1dDzvmhRzXVvyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OVRxazZWdmwrQ1JBeWlI
            UXF3b0Nyc2VzdWcyaTdjUzBNV21QMHp0cEMwCkdoWFlBNm40MGNiVStnbE1HUTdv
            Yi9SRWlCVjBuYlNwZkxwQk8zWnB3UVUKLS0tIENwMlMrUGFPcWFXQitGckhIS1Bt
            NHJoc2hBa2E2ak1zdTNISTc4VTRvUE0KHg5tiGkKDDhoiGNT3Z8pxIdCHeD+lFGN
            +WGIh8ezw06U2c52qX7YI+zpjys/V3syvh45tE780BcR5atveEIizQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-21T17:27:58Z"
    mac: ENC[AES256_GCM,data:tkacGFrl9niAJYTAT8Z+qaK4wDPYwnDNUAJIyiuAXI6vAi6PDN0MA226SCDSn7rjASlmQFXBIr0pOrO+p6tIF2k8j3TzcvtxoGAXhCKE5E6HvD1CCoHeeRtk+Iw0f/NM1WGc3uw/o/uogXDJ1DE+TuylUGDwxJKEwqzUJ8oB++4=,iv:NXP6Tb6QgoO+MBdCpV6Gi8zaGwgCc6e5dO8wtsaUsrQ=,tag:XI5HI8j6NpuGKGG7KaM9ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
