apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:1q47Rj7qv63U9SSy0Jn0YuzXVlniu5FbtvbFnWsHPbg=,iv:UVYGx5NZn48xTroPOqdURBC0L22+CSFJ7hvp2YJYh0M=,tag:ePKh9EL3GMeeAOoxTXimUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SlRwbm9BU0ExT0JyakNJ
            SStkNWRHYVFYemk2QTE1QVdVYnV3OGpIRDFBCit1RElGK2w1M3kxTHEyRnNhamxy
            eFN2WUNwTUhGZGlQSk9ZY2JzRUdNK0kKLS0tIFl3ZVdxbWJVemZzMnJRU3FjN0N4
            K1dqRzAwdFM0cEY3MVU1Y0kwN3E1ZHMKj9o9MDKM/P+qAjJqN6fJ7WL9AjMtwT7r
            JwhiZX/Ld88Zq31MTljDu88k4/MjdUzsja0lYpWKPiAVEF14BQvdcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-20T16:31:45Z"
    mac: ENC[AES256_GCM,data:33Z0OA6n/QFgOK2raFEQcdL/BywYO560Xl5zg5XnKKo1Ft5LKJPJCzrGxVf4/R49Vom+BbhKJ1TiTw5lWPtopDjn6J19Q41MY690XZPVYcvB94qWkbIK10by4r2W3W/zi4qfyqwXMp82jTXSmRMrK3gggG6yN1t5SfuMvEgWSR8=,iv:vv8HLuiZQpxzBISywvqY4zacCYi8mi8p0JpLcVQSoWM=,tag:LqR0nwgnaJom62rTc0mYfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
