apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:a/K9iZw1YgQvtw7Il5nlr18sQlYnrf13QTEbQRJQOdM=,iv:r4oD5EH91RZ270aVGtSJgWALuhV3ejP+my3HN/hE72Q=,tag:8MCcK25HS38fVC2dvSwWYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK2FhWnRuSGhmbkxoSVpj
            bkRxU3RlOGNCODA0Z3hkVGpyVFpXcjdwWGlFCnRrV2U3YnRua29oTFMzVmJVcXNo
            Wnlzak9kd0ZrQzF0T2RmSEtraVFPNWMKLS0tIGh4Nkk4d0FzUkFGalNaOWZ1VmVI
            NDdHb3YzMWtiVTQxT1FnZ2J5RThzSFkKi0rF4LeDZgcOzAVVHqLhRz1IrfUJ/HEb
            YIyW+1yhWg56wuHEQzuwsQGbaCXBkV55uRKzsVQZekejNUSUNOpXOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T14:04:29Z"
    mac: ENC[AES256_GCM,data:Cm7Wa/UqJqge3hdAIOUEXTBuqfFuc9vI774PsvRPe7lVrwTpOAAeNSfyE7bD//D21CbgelPobLzTWvlBRKl04xKRc3dSklnV7DPMAU6ve9Ceqx4kAmaOUUIMqh5uZlFC+xfNp3K9eRI9Yzx+oPFR9Wn/TJlhWJ8TbZL+kt0dAhA=,iv:XziZxBYARcRGWsQZF9BXw7rPrmD7OIvjQfXRpapAjsA=,tag:hZADv2ZXxRhUWaEQMzkaRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
