apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:zifntbF2WDDr8v6xNcpY1N+2uEZT2ny3f/SF7WtGdes=,iv:3CBtAjYrVskzXm885wyi3piNh4EdQQaHqdk+vpON2I8=,tag:PZDuocimQGdXzvVqQ5WMZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Ti9LN045YU8xcU1YWSt0
            S1FpK080ck9Zemw3MXA3UHJ5QjMvaklCcUFJClNsZG5PZHZ6dE9NTytJUWFUZ1pK
            NDhzRHJBdnlXSjhLUkVKdnFOVFEwdEkKLS0tIENjYy8rRm9CUE1tbnpobDVBK09B
            YlJ5UFRzNm5xd01Mak5sS0VkSXd1VUkKLBpC5QrZKsGXPFtJtjzbGV/N7dowG/gZ
            L4S1xO2iuaC2iV6oUGQEgiOxGA5cYZrqDw2goloFSgh3mWS/d9lDXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T19:32:32Z"
    mac: ENC[AES256_GCM,data:ZoiVsdE4knJXG73URFMpFk/9k1+F5IUDBpbn2YN3DkQhUTY2dR9XeGTCbyKkPqkKGfL6LruqLDEknUXFDpYan9PQvdYLNnD7Nrf0eNr+agXfRW7NqYl4GMKrHs3iq4XSLaXPubmoMinWxV43P90E7h6MZycdGp/Q5Mgfu839jp8=,iv:aVXV+yI1ri3cmme4Smvb5nDEEVk0GQIBaGwoocx9sHE=,tag:ZIv8ZqiwxSd9R61yE6j31A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
