apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:dm5x8vAbN6YEr90Q4+WKC61CfmoSZUXjYhzKlcSsVh1jaVq0JPYkcQ==,iv:xvBTCP3HojJJvLZJj1AT4U59dg5t+JHvJ68U4WSxmiQ=,tag:nBXAeJK4NV2CSgilgJZEog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNTBqOGdoZzc0MGk1eHg0
            Q0tLbXRFZTRUVHY4SmtDUXhnUkV1OUs0Q0YwCkM0YllxUE1pWnRHdW5oWXFXMVcw
            QjNIV09sVjRrTWdLN05meStxU0hETGMKLS0tIDBIUWtXUDJLdTJRdDZwb0pMZXZi
            Wng1bFl4eFk2WTkyZkgwWmVPbEFaUzAKcFWSVXzcvUXKZvzkbhoULkPMJFgHLOoY
            JPZLSNZnu4ABoySLkJ6chhg33FUOy7p7qsvpTvDKAMmmCDdoGmMshA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T17:22:51Z"
    mac: ENC[AES256_GCM,data:vkYurod6IzZRQi2OaHLipz4Zt7Ovhxvj63bsgx6zdttgZtxrwyWF8AxOiYDNH6u+qAQy8Xu4gsxYUVOnNs1LMPF1Q8NxACaaK0ztlKm54YnabHy7nZUBwNsdQTxTjkeHmRvu6Qis5qmPf/yb6JYuT3kK+p2wEISjfdyU0NTaKBs=,iv:DFuLjuUB9iQMhH+nwq1WaA8dmw3xX3mWrrab1s8WouI=,tag:IzWuhpLVrDmm9UR6/CK9vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
