apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:kwFNT/e4sSK+Xok917qQmSY3QWx18FBemXeZQ+lhhUhXiQ8q4Jf5Gw==,iv:cZlhbD8zJK6/CxLKP9uKw9nh+w+jPZAo+ZtS2+Ok01Q=,tag:Ygi7ljZGlgN8Tl7GV8tWgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV1FKUlBmWnk0RkVGWlBW
            dXcxTXlhRHpkOTl2d1F3Tk43cDlLT3hpcUhJCktVQVN5VDQwVk0vQnpyN2NSd1pu
            RkVTTnliMjd5Q3ovRTJxNzBSTk04MzQKLS0tIHA1bGwxcFVMbmE1aUNlQi9QRE8w
            YjNEQ09mZm55dWlEdGJHc0xKVTE5MjAKsJsKBglvK8bvDyPDz10Z9FbM6rx3xS7c
            /M3PFF7CEsYXj2azX7lRy7u3vJFq7eJwtBGw9XqX+VBYKEx3UQjNCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T19:42:08Z"
    mac: ENC[AES256_GCM,data:KCek5ot8z4ZKqDpuIY9w4w9GiKy2ptP2fGZfJ12gOf6gvKhXaLOmtinRIP7RzLuDe+6IywscSjlAtOQHGsJLYvhCNgTZ/G4gCrgH7lmf9ZK4MPmr5oQQF7+gDUrOtkNSzFbeaSLJW6FVnmNPEheRIy7wCFCjBVrigDzdROirGFY=,iv:tMOFkT3MTsb0uMrZVMFcdupwAxHvmh5X5z55sfTkaS4=,tag:RVi5JhAeO8vWqARVpA2ReQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
