apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Vk1qpYySP9e+VQkG/y7ZIfy2CUVeHcjBiZjyVTtI4ufMnH6rp5rogA==,iv:ckPMHe8YFrz7ZkpxUQLBKEr430zM2JXGRZuADsTBR8I=,tag:gBdiKe5W3Nb+iVJ18FXUxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S2tKb003MC9EdzdOMk56
            Qm8zSThLRHg5Q0FVTWVEa25BZ2drZ0tFVDFrCjg5QXZRM2NOcDF4THVNdTU5UFV4
            UjVYV2xsRHNMWEY4MnU3b01peUNnRXMKLS0tIGhtbWY1NmRmUVdPQU1hQjIrUXZv
            UGRmQzJ0NDlWVWdiWXZGSzBrZFg4M2MKZFiO5Wbfiokn1yn7GDUXMrdAAPJrzA8g
            FD8Gs6jatvAslc28lGjrOpBaBnyp3/fKzImZIzCE0937DdROg6VyLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-24T14:52:36Z"
    mac: ENC[AES256_GCM,data:SUUdbgQf5JXfr1b9yYbgGD9wNkVmLzhp37qc/8ZHTK3kOM5m9nOtxwcmJL/ZYzpLLtAyLi8sZguk/6O+fyRkLKg6vicgEr9iNFaMpSyOdsWZtWW/mpVCfhrqKIMoTGPldRfTX9oxCV6B3qR+avd+dA0m0Dvw2m9lbaQCU+Dt8MQ=,iv:GujevTva4MgQVBw/kYVjP/x60hDPWC3uC2pK9TWOtUA=,tag:whBLNIbN5oqkbOxSFKWo7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
